-- Migration: Enhanced Detailed Product Data Part 2
-- Continuation of detailed products for remaining categories
-- All products include Indian brands, specific styles, size variations, and realistic pricing
-- All prices are in Indian Rupees (INR)

-- ============================================
-- 3. KIDS & TOYS (35+ products)
-- Brands: Gini & Jony, Lilliput, Funskool, Hamleys | Age Groups: 2-12 years
-- Price Range: ₹199 - ₹2999 | Sizes: 2-3Y, 4-5Y, 6-7Y, 8-9Y, 10-11Y, 12Y
-- ============================================
INSERT INTO public.products (name, description, price, category_id, subcategory, image_url, stock) VALUES
  -- Kids Clothing (12 products)
  ('Gini & Jony Boys Cotton T-Shirt Set - Pack of 3', 'Gini & Jony comfortable cotton t-shirt set for boys. Pack of 3 with vibrant colors. Available in sizes: 3-4Y, 5-6Y, 7-8Y, 9-10Y, 11-12Y. Colors: Blue, Red, Green, Yellow. Fabric: 100% Pure Cotton', 599, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800', 50),
  ('Lilliput Girls Frock Dress - Floral', 'Lilliput beautiful floral frock dress for girls. Perfect for parties and special occasions. Sizes: 2-3Y, 4-5Y, 6-7Y, 8-9Y, 10-11Y. Colors: Pink, Blue, Yellow, Purple. Fabric: Soft Cotton', 899, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800', 40),
  ('Gini & Jony Kids Denim Jeans - Durable', 'Gini & Jony durable denim jeans for kids. Comfortable fit with stretch. Available in sizes 3-12 years. Colors: Blue, Black, Grey. Fabric: Premium Denim with Stretch', 799, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800', 45),
  ('Lilliput Kids Track Suit - Sports', 'Lilliput comfortable track suit for active kids. Perfect for sports and outdoor activities. Sizes: 4-5Y, 6-7Y, 8-9Y, 10-11Y. Colors: Blue, Red, Black, Grey. Fabric: Polyester-Cotton Blend', 1299, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800', 35),
  ('Gini & Jony Kids Kurta Set - Traditional', 'Gini & Jony traditional kurta set for kids. Perfect for festivals and special occasions. Available in sizes 3-10 years. Colors: White, Cream, Beige, Light Blue. Fabric: Pure Cotton', 699, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800', 42),
  ('Lilliput Girls Lehenga Choli - Party', 'Lilliput beautiful lehenga choli set for girls. Perfect for parties and celebrations. Sizes: 3-4Y, 5-6Y, 7-8Y, 9-10Y. Colors: Pink, Red, Blue, Purple. Fabric: Premium Georgette with Embroidered Work', 1999, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800', 30),
  ('Gini & Jony Kids Winter Jacket - Warm', 'Gini & Jony warm winter jacket for kids. Quilted design with hood. Available in sizes 4-12 years. Colors: Red, Blue, Black, Navy. Fabric: Polyester with Padding', 1499, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800', 38),
  ('Lilliput Kids School Uniform Set', 'Lilliput complete school uniform set. Includes shirt and pants/skirt. Sizes: 4-5Y, 6-7Y, 8-9Y, 10-11Y. Colors: White shirt with Navy/Grey pants/skirt. Fabric: Premium Cotton', 999, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800', 50),
  ('Gini & Jony Kids Casual Shorts - Summer', 'Gini & Jony comfortable casual shorts for summer. Perfect for playtime. Available in sizes 3-10 years. Colors: Khaki, Navy, Grey, Beige. Fabric: Soft Cotton', 499, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800', 55),
  ('Lilliput Girls Party Dress - Fancy', 'Lilliput fancy party dress for girls. Beautiful design with frills and decorations. Sizes: 3-4Y, 5-6Y, 7-8Y, 9-10Y. Colors: Pink, Purple, Blue, Red. Fabric: Premium Chiffon', 1599, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800', 28),
  ('Gini & Jony Kids Pajama Set - Comfort', 'Gini & Jony comfortable pajama set for kids. Soft fabric for good sleep. Available in sizes 3-12 years. Colors: Blue, Pink, Green, Yellow. Fabric: Soft Cotton', 599, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800', 48),
  ('Lilliput Kids Raincoat - Waterproof', 'Lilliput waterproof raincoat for kids. Perfect for monsoon season. Sizes: 4-5Y, 6-7Y, 8-9Y, 10-11Y. Colors: Yellow, Blue, Red, Green. Fabric: Waterproof Polyester', 799, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800', 40),
  
  -- Toys (12 products)
  ('Funskool Building Blocks Set - Educational', 'Funskool educational building blocks set with 100+ pieces. Develops creativity and motor skills. Suitable for ages 3-8 years. Colors: Multi-color. Material: Safe Plastic', 899, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 35),
  ('Hamleys Remote Control Car - Electric', 'Hamleys electric remote control car with LED lights. High-speed performance. Suitable for ages 6+. Colors: Red, Blue, Yellow, Black. Material: Durable Plastic', 1299, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 30),
  ('Funskool Doll House - Complete Set', 'Funskool complete doll house with furniture and accessories. Perfect for pretend play. Suitable for ages 4-10 years. Material: Durable Plastic', 2499, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 20),
  ('Hamleys Action Figure Set - Superhero', 'Hamleys superhero action figure set with accessories. Multiple characters available. Suitable for ages 5+. Material: Durable Plastic', 599, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 45),
  ('Funskool Puzzle Set - 500 Pieces', 'Funskool educational puzzle set with 500 pieces. Improves problem-solving skills. Suitable for ages 8+. Multiple design options. Material: Cardboard', 699, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 40),
  ('Hamleys Musical Toy Piano - Keyboard', 'Hamleys musical keyboard piano for kids. Develops musical skills. Suitable for ages 3+. Colors: Pink, Blue, White. Material: Durable Plastic', 1499, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 25),
  ('Funskool Soft Toy Bear - Plush', 'Funskool soft plush teddy bear. Perfect companion for kids. Available in multiple sizes: Small, Medium, Large. Colors: Brown, Pink, Blue, White. Material: Soft Plush', 499, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 50),
  ('Hamleys LEGO Style Building Set', 'Hamleys compatible building blocks set with 200+ pieces. Encourages creativity. Suitable for ages 5-12 years. Multiple color options. Material: Safe Plastic', 1799, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 32),
  ('Funskool Board Game - Snakes & Ladders', 'Funskool classic Snakes and Ladders board game. Family fun time. Suitable for ages 4+. 2-4 players. Material: Cardboard', 399, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 55),
  ('Hamleys Toy Kitchen Set - Pretend Play', 'Hamleys complete toy kitchen set for pretend play. Includes multiple accessories. Suitable for ages 3-8 years. Material: Durable Plastic', 1999, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 28),
  ('Funskool RC Helicopter - Mini', 'Funskool mini remote control helicopter with LED lights. Easy to control. Suitable for ages 8+. Colors: Red, Blue, Black. Material: Lightweight Plastic', 1599, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 22),
  ('Hamleys Art & Craft Set - Complete', 'Hamleys complete art and craft set with colors, brushes, and papers. Encourages creativity. Suitable for ages 5+. Multiple color options. Material: Safe Non-Toxic Materials', 799, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 38),
  
  -- School Supplies (6 products)
  ('Skybags School Bag - Backpack Style', 'Skybags durable school backpack with multiple compartments. Ergonomic design. Available in sizes: Small, Medium, Large. Colors: Blue, Red, Black, Pink, Grey. Material: Durable Polyester', 899, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'School Supplies', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 40),
  ('Cello Lunch Box Set - Bento Style', 'Cello bento style lunch box set with water bottle. Leak-proof design. Colors: Blue, Pink, Green, Yellow, Red. Material: Food-Grade Plastic', 599, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'School Supplies', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 45),
  ('Apsara Geometry Box - Complete', 'Apsara complete geometry box with compass, protractor, and ruler. Essential for students. Suitable for ages 8+. Colors: Blue, Red, Black. Material: Durable Plastic and Metal', 299, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'School Supplies', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 60),
  ('Classmate Pencil Case - Zipper', 'Classmate zipper pencil case with multiple compartments. Organizes stationery. Colors: Blue, Pink, Black, Red, Green. Material: Durable Polyester', 199, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'School Supplies', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 70),
  ('Milton Water Bottle - Stainless Steel', 'Milton stainless steel water bottle with leak-proof cap. Keeps drinks cool. Available in 500ml and 750ml. Colors: Blue, Pink, Green, Black. Material: Food-Grade Stainless Steel', 499, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'School Supplies', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 50),
  ('Classmate Notebook Set - Pack of 5', 'Classmate set of 5 ruled notebooks (200 pages each). Essential for school. Suitable for all ages. Multiple cover colors. Material: Quality Paper', 399, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'School Supplies', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 55),
  
  -- Games (5 products)
  ('Funskool Chess Set - Wooden', 'Funskool classic wooden chess set with board. Develops strategic thinking. Suitable for ages 8+. Complete with all pieces. Material: Premium Wood', 799, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Games', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 35),
  ('Hamleys Carrom Board - Professional', 'Hamleys professional carrom board with striker and coins. Traditional Indian game. Suitable for ages 6+. 2-4 players. Material: Premium Wood', 1499, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Games', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 25),
  ('Funskool Ludo Game Set - Classic', 'Funskool classic Ludo game set with dice and tokens. Family favorite. Suitable for ages 4+. 2-4 players. Material: Durable Cardboard', 499, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Games', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 40),
  ('Hamleys Card Game Set - Multiple Games', 'Hamleys card game set with multiple games (Uno, Rummy, etc.). Hours of fun. Suitable for ages 6+. Multiple game options. Material: Quality Cardboard', 599, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Games', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 38),
  ('Funskool Jigsaw Puzzle - 1000 Pieces', 'Funskool challenging 1000-piece jigsaw puzzle. Improves concentration. Suitable for ages 10+. Multiple design options. Material: Durable Cardboard', 899, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Games', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 30);

-- ============================================
-- 4. HOME & KITCHEN (35+ products)
-- Brands: Prestige, Pigeon, Cello, Milton | Types: Cookware, Storage, Appliances
-- Price Range: ₹299 - ₹4999 | Sizes: Various (Small, Medium, Large, Sets)
-- ============================================
INSERT INTO public.products (name, description, price, category_id, subcategory, image_url, stock) VALUES
  -- Kitchenware (12 products)
  ('Prestige Non-Stick Cookware Set - 5 Pieces', 'Prestige premium non-stick cookware set with 5 pieces. Includes fry pan, kadai, tawa, and lids. Colors: Black, Red, Blue. Material: Hard Anodized with Non-Stick Coating', 2499, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 30),
  ('Pigeon Stainless Steel Pressure Cooker - 5L', 'Pigeon durable stainless steel pressure cooker 5L capacity. Saves time and energy. Suitable for 4-6 people. Silver finish. Material: Premium Stainless Steel', 1299, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 35),
  ('Cello Ceramic Dinner Set - 24 Pieces', 'Cello beautiful ceramic dinner set with 24 pieces. Includes plates, bowls, and mugs. Colors: White, Blue, Green. Material: Premium Ceramic', 1999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 28),
  ('Milton Glass Storage Containers Set - 10 Pieces', 'Milton airtight glass storage containers set. Keeps food fresh. Available in multiple sizes. Perfect for food storage. Material: Borosilicate Glass', 899, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 40),
  ('Prestige Knife Set - 6 Pieces', 'Prestige premium stainless steel knife set with wooden block. Includes chef knife, bread knife, and utility knives. Material: High-Carbon Stainless Steel', 1499, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 32),
  ('Pigeon Cutting Board Set - Bamboo', 'Pigeon eco-friendly bamboo cutting board set. Includes 3 different sizes. Natural finish. Material: Premium Bamboo', 599, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 45),
  ('Cello Silicone Spatula Set - 5 Pieces', 'Cello heat-resistant silicone spatula set. Includes various sizes and shapes. Colors: Red, Blue, Green, Black. Material: Food-Grade Silicone', 399, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 50),
  ('Milton Steel Tiffin Box - 3 Tier', 'Milton stainless steel 3-tier tiffin box. Leak-proof design. Perfect for lunch. Silver finish. Material: Food-Grade Stainless Steel', 699, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 42),
  ('Prestige Coffee Maker - Electric', 'Prestige electric coffee maker with auto shut-off. Perfect morning coffee. Capacity: 1.25L. Colors: Black, White, Red. Material: Stainless Steel and Plastic', 2499, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 25),
  ('Pigeon Mixer Grinder - 750W', 'Pigeon powerful 750W mixer grinder with 3 jars. Perfect for Indian cooking. Stainless steel blades. Colors: White, Red, Blue. Material: Stainless Steel Jars', 2999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 22),
  ('Cello Kitchen Scale - Digital', 'Cello digital kitchen scale with LCD display. Precise measurements. Capacity: 5kg. Precision: 1g. Colors: White, Black. Material: Durable Plastic', 799, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 38),
  ('Milton Steel Utensil Set - 12 Pieces', 'Milton complete stainless steel utensil set. Includes spoons, ladles, and serving spoons. Silver finish. Material: Premium Stainless Steel', 1299, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 35),
  
  -- Home Decor (8 products)
  ('Titan Wall Clock - Modern Design', 'Titan modern wall clock with silent movement. Elegant design. Available in 12" and 15" sizes. Colors: Black, White, Brown, Silver. Material: Premium Plastic and Metal', 899, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Home Decor', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 40),
  ('Philips Table Lamp - LED', 'Philips energy-efficient LED table lamp with adjustable brightness. Perfect for study and work. Colors: White, Black, Gold, Silver. Material: Metal and Plastic', 699, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Home Decor', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 35),
  ('Cello Photo Frame Set - 6 Pieces', 'Cello set of 6 photo frames in different sizes. Wooden and metal options. Colors: Brown, Black, White, Gold. Material: Wood and Metal', 599, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Home Decor', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 45),
  ('Home Centre Curtain Set - Ready Made', 'Home Centre ready-made curtain set with matching valance. Beautiful designs. Available in multiple sizes. Colors: Beige, Blue, Grey, Brown. Material: Premium Fabric', 1299, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Home Decor', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 30),
  ('Fabindia Wall Art - Canvas Print', 'Fabindia beautiful canvas wall art print. Indian traditional designs. Multiple designs available. Sizes: 12x16, 16x20, 20x24 inches. Material: Canvas', 799, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Home Decor', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 38),
  ('Cello Vase Set - Ceramic', 'Cello elegant ceramic vase set. Includes 3 different sizes. Colors: White, Blue, Green, Terracotta. Material: Premium Ceramic', 499, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Home Decor', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 42),
  ('Home Centre Cushion Cover Set - 4 Pieces', 'Home Centre decorative cushion cover set with 4 pieces. Multiple designs and colors available. Material: Premium Cotton', 399, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Home Decor', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 50),
  ('Fabindia Rug - Area Carpet', 'Fabindia soft area rug for living room. Traditional Indian designs. Available in multiple sizes. Colors: Beige, Grey, Blue, Brown. Material: Premium Wool Blend', 1999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Home Decor', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 28),
  
  -- Furniture (5 products)
  ('Godrej Study Table - Wooden', 'Godrej durable wooden study table with drawer. Perfect for home office. Colors: Brown, White, Black. Material: Engineered Wood', 3999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Furniture', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 20),
  ('Nilkamal Dining Chair Set - 4 Pieces', 'Nilkamal comfortable dining chair set with 4 chairs. Upholstered seats. Colors: Brown, Black, Beige. Material: Engineered Wood with Upholstery', 4999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Furniture', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 18),
  ('Godrej Bookshelf - 5 Tier', 'Godrej spacious 5-tier bookshelf. Organizes books and display items. Colors: Brown, White, Black. Material: Engineered Wood', 2999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Furniture', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 22),
  ('Nilkamal Coffee Table - Glass Top', 'Nilkamal modern coffee table with glass top. Elegant design. Wooden base. Colors: Brown, Black, White. Material: Glass Top with Engineered Wood Base', 3499, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Furniture', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 25),
  ('Godrej Shoe Rack - Metal', 'Godrej sturdy metal shoe rack with 4 tiers. Space-saving design. Colors: Black, White, Silver. Material: Durable Metal', 1499, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Furniture', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 30),
  
  -- Appliances (5 products)
  ('Pigeon Electric Kettle - 1.5L', 'Pigeon stainless steel electric kettle with auto shut-off. Quick boiling. Capacity: 1.5L. Colors: White, Black, Silver. Material: Stainless Steel', 999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Appliances', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 35),
  ('Prestige Toaster - 2 Slice', 'Prestige 2-slice toaster with multiple browning settings. Perfect breakfast companion. Colors: White, Black, Red, Silver. Material: Stainless Steel', 1299, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Appliances', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 32),
  ('Philips Iron - Steam', 'Philips steam iron with non-stick soleplate. Easy ironing. Power: 1200W. Colors: White, Blue, Pink, Black. Material: Non-Stick Soleplate', 899, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Appliances', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 40),
  ('Usha Table Fan - 16 Inch', 'Usha 16-inch table fan with 3-speed settings. Oscillating feature. Colors: White, Black, Grey. Material: Durable Plastic', 1499, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Appliances', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 28),
  ('Philips Air Purifier - HEPA Filter', 'Philips HEPA air purifier for rooms up to 300 sq ft. Clean air technology. Multiple filter stages. Colors: White, Black. Material: Premium Plastic', 4999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Appliances', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 15),
  
  -- Bedding (5 products)
  ('Home Centre Bed Sheet Set - Cotton', 'Home Centre premium cotton bed sheet set. Includes bed sheet, pillow covers. Sizes: Single, Double, King. Colors: White, Blue, Pink, Beige. Material: 100% Pure Cotton', 1299, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Bedding', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 35),
  ('Spaces Comforter Set - All Season', 'Spaces all-season comforter set with matching pillow covers. Comfortable and warm. Sizes: Single, Double, King. Colors: Blue, Grey, Beige, White. Material: Polyester Filling', 2499, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Bedding', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 28),
  ('Sleepwell Pillow Set - Memory Foam', 'Sleepwell memory foam pillow set of 2. Orthopedic support. Sizes: Standard, Queen, King. Material: Memory Foam', 899, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Bedding', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 40),
  ('Home Centre Mattress Protector - Waterproof', 'Home Centre waterproof mattress protector. Fitted sheet style. Sizes: Single, Double, King. Colors: White, Beige. Material: Waterproof Polyester', 699, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Bedding', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 45),
  ('Spaces Blanket - Fleece', 'Spaces soft fleece blanket. Warm and cozy. Available in multiple sizes. Colors: Blue, Grey, Beige, Pink, White. Material: Premium Fleece', 999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Bedding', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 38);

-- Continue with remaining categories in next section...


