-- Migration: Enhanced Detailed Product Data for All Categories
-- This migration replaces existing products with detailed, category-specific products
-- All products include Indian brands, specific styles, size variations, and realistic pricing
-- All prices are in Indian Rupees (INR)

-- First, delete existing products (to avoid foreign key issues)
DELETE FROM public.products;

-- Ensure categories exist (run category migration first if needed)

-- ============================================
-- 1. KURTIS, SAREES & LEHENGAS (35+ products)
-- Styles: Anarkali, A-line, Straight | Fabrics: Cotton, Silk, Chiffon, Georgette
-- Price Range: ₹299 - ₹4999 | Sizes: S, M, L, XL
-- ============================================
INSERT INTO public.products (name, description, price, category_id, subcategory, image_url, stock) VALUES
  -- Kurtis - Anarkali Style (8 products)
  ('Fabindia Cotton Anarkali Kurti - Printed', 'Fabindia cotton Anarkali kurti with traditional Indian prints. Flared silhouette, perfect for festive occasions. Available in sizes S, M, L, XL. Colors: Red, Blue, Green, Yellow, Pink. Fabric: 100% Pure Cotton', 899, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 45),
  ('W for Woman Silk Anarkali Kurti - Embroidered', 'W for Woman premium silk Anarkali kurti with intricate hand embroidery. Elegant flared design with side slits. Sizes: S, M, L, XL. Colors: Maroon, Navy, Teal, Purple, Gold. Fabric: Pure Silk', 2499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 30),
  ('Biba Chiffon Anarkali Kurti - Party Wear', 'Biba designer chiffon Anarkali kurti with sequin and mirror work. Perfect for parties and celebrations. Available in S, M, L, XL. Colors: Black, Royal Blue, Wine, Emerald, Gold. Fabric: Premium Chiffon', 1899, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 35),
  ('Manyavar Georgette Anarkali Kurti - Designer', 'Manyavar elegant georgette Anarkali kurti with modern prints. Flowing silhouette with beautiful drape. Sizes: S, M, L, XL. Colors: Grey, Beige, Rose, Turquoise, Peach. Fabric: Premium Georgette', 1299, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 40),
  ('Allen Solly Cotton Anarkali Kurti - Casual', 'Allen Solly comfortable cotton Anarkali kurti for daily wear. Simple yet elegant design. Available in S, M, L, XL. Colors: White, Black, Brown, Olive, Navy. Fabric: Soft Cotton', 599, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 55),
  ('Soch Silk Anarkali Kurti - Traditional', 'Soch traditional silk Anarkali kurti with zari border work. Perfect for traditional occasions. Sizes: S, M, L, XL. Colors: Red, Green, Gold, Blue, Maroon. Fabric: Pure Silk', 2999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 28),
  ('Global Desi Chiffon Anarkali Kurti - Contemporary', 'Global Desi contemporary chiffon Anarkali kurti with modern motifs. Trendy design for young women. Available in S, M, L, XL. Colors: Coral, Mint, Lavender, Rose, Turquoise. Fabric: Lightweight Chiffon', 1499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 38),
  ('Wrangler Cotton Anarkali Kurti - Comfort', 'Wrangler comfortable cotton Anarkali kurti with side slits. Perfect for everyday casual wear. Sizes: S, M, L, XL. Colors: Indigo, Rust, Mint, Peach, Mustard. Fabric: Breathable Cotton', 699, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 50),
  
  -- Kurtis - A-Line Style (8 products)
  ('Fabindia Cotton A-Line Kurti - Printed', 'Fabindia comfortable A-line cotton kurti with beautiful Indian prints. Flattering fit for all body types. Available in S, M, L, XL. Colors: Red, Blue, Green, Yellow, Pink. Fabric: Pure Cotton', 799, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 48),
  ('W for Woman Silk A-Line Kurti - Embroidered', 'W for Woman elegant silk A-line kurti with handcrafted embroidery. Perfect for office and parties. Sizes: S, M, L, XL. Colors: Burgundy, Charcoal, Ivory, Plum, Navy. Fabric: Premium Silk', 2199, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 32),
  ('Biba Chiffon A-Line Kurti - Party', 'Biba stylish chiffon A-line kurti with sequin work. Great for parties and celebrations. Available in S, M, L, XL. Colors: Black, Navy, Wine, Emerald, Royal Blue. Fabric: Premium Chiffon', 1799, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 36),
  ('Manyavar Georgette A-Line Kurti - Modern', 'Manyavar modern georgette A-line kurti with contemporary prints. Comfortable and stylish. Sizes: S, M, L, XL. Colors: Grey, Beige, Rose, Turquoise, Coral. Fabric: Premium Georgette', 999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 42),
  ('Allen Solly Cotton A-Line Kurti - Daily Wear', 'Allen Solly simple cotton A-line kurti for everyday wear. Comfortable fit with side slits. Available in S, M, L, XL. Colors: White, Black, Brown, Olive, Grey. Fabric: Soft Cotton', 499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 60),
  ('Soch Silk A-Line Kurti - Traditional', 'Soch traditional silk A-line kurti with zari work. Perfect for traditional occasions. Sizes: S, M, L, XL. Colors: Red, Green, Gold, Blue, Maroon. Fabric: Pure Silk', 2799, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 30),
  ('Global Desi Chiffon A-Line Kurti - Contemporary', 'Global Desi contemporary chiffon A-line kurti with modern design. Trendy and comfortable. Available in S, M, L, XL. Colors: Peach, Mint, Lavender, Coral, Rose. Fabric: Lightweight Chiffon', 1399, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 38),
  ('Wrangler Cotton A-Line Kurti - Casual', 'Wrangler casual cotton A-line kurti with comfortable fit. Perfect for daily wear. Sizes: S, M, L, XL. Colors: Orange, Magenta, Cyan, Mustard, Rust. Fabric: Breathable Cotton', 599, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 52),
  
  -- Kurtis - Straight Style (6 products)
  ('Fabindia Cotton Straight Kurti - Printed', 'Fabindia elegant straight cut cotton kurti with Indian prints. Perfect for office wear. Available in S, M, L, XL. Colors: Red, Blue, Green, Yellow, Pink. Fabric: Pure Cotton', 699, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 46),
  ('W for Woman Silk Straight Kurti - Formal', 'W for Woman premium silk straight kurti. Perfect for formal occasions and office. Sizes: S, M, L, XL. Colors: Burgundy, Charcoal, Ivory, Plum, Navy. Fabric: Premium Silk', 1999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 34),
  ('Biba Chiffon Straight Kurti - Designer', 'Biba designer chiffon straight kurti with mirror work. Elegant and sophisticated. Available in S, M, L, XL. Colors: Black, Navy, Wine, Emerald, Royal Blue. Fabric: Premium Chiffon', 1699, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 37),
  ('Manyavar Georgette Straight Kurti - Modern', 'Manyavar modern georgette straight kurti with contemporary prints. Versatile style. Sizes: S, M, L, XL. Colors: Grey, Beige, Rose, Turquoise, Coral. Fabric: Premium Georgette', 899, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 44),
  ('Allen Solly Cotton Straight Kurti - Casual', 'Allen Solly comfortable cotton straight kurti for daily wear. Simple and elegant. Available in S, M, L, XL. Colors: White, Black, Brown, Olive, Grey. Fabric: Soft Cotton', 449, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 58),
  ('Soch Silk Straight Kurti - Traditional', 'Soch traditional silk straight kurti with zari border. Perfect for traditional events. Sizes: S, M, L, XL. Colors: Red, Green, Gold, Blue, Maroon. Fabric: Pure Silk', 2599, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 29),
  
  -- Sarees (8 products)
  ('Fabindia Cotton Handloom Saree - Traditional', 'Fabindia traditional handloom cotton saree with beautiful border work. Authentic Indian craftsmanship. Available in multiple colors: Red, Green, Blue, Yellow, Orange. Fabric: Pure Cotton Handloom', 1999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1594633312681-425c7b7ccd1?w=800', 25),
  ('Soch Silk Kanjivaram Saree - Authentic', 'Soch authentic Kanjivaram silk saree with intricate zari work. Premium quality traditional saree. Colors: Maroon, Green, Gold, Blue, Purple. Fabric: Pure Kanjivaram Silk', 4999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 15),
  ('Biba Georgette Designer Saree - Wedding', 'Biba elegant georgette designer saree with matching blouse. Perfect for weddings and special occasions. Colors: Pink, Peach, Mint, Lavender, Coral. Fabric: Premium Georgette', 3499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 20),
  ('Manyavar Chiffon Party Saree - Sequin', 'Manyavar stylish chiffon party saree with sequin and stone work. Great for parties. Colors: Black, Navy, Wine, Emerald, Royal Blue. Fabric: Premium Chiffon', 2499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 22),
  ('W for Woman Cotton Printed Saree - Modern', 'W for Woman comfortable cotton printed saree with modern designs. Ideal for daily wear. Colors: White, Grey, Beige, Brown, Olive. Fabric: Pure Cotton', 1299, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 30),
  ('Soch Silk Banarasi Saree - Brocade', 'Soch traditional Banarasi silk saree with intricate brocade work. Premium wedding saree. Colors: Red, Green, Gold, Blue, Maroon. Fabric: Pure Banarasi Silk', 4999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 18),
  ('Biba Organza Embroidered Saree - Luxury', 'Biba luxurious organza saree with hand embroidery. Perfect for special occasions. Colors: Ivory, Peach, Mint, Lavender, Gold. Fabric: Premium Organza', 3999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 16),
  ('Fabindia Linen Handloom Saree - Traditional', 'Fabindia elegant linen handloom saree with traditional motifs. Comfortable and stylish. Colors: Cream, Khaki, Terracotta, Sage, Beige. Fabric: Pure Linen Handloom', 2999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 24),
  
  -- Lehengas (5 products)
  ('Manyavar Designer Lehenga Choli - Embroidered', 'Manyavar beautiful designer lehenga choli set with intricate embroidery and matching dupatta. Perfect for weddings. Available in sizes S, M, L, XL. Colors: Red, Pink, Blue, Green, Purple. Fabric: Premium Silk with Embroidered Work', 4999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 15),
  ('Soch Bridal Lehenga Set - Heavy Work', 'Soch stunning bridal lehenga with heavy zari and embroidery work. Perfect for weddings. Sizes: S, M, L, XL. Colors: Red, Maroon, Gold, Pink, Peach. Fabric: Premium Silk with Heavy Work', 4999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 12),
  ('Biba Party Lehenga Choli - Sequin', 'Biba elegant party lehenga with sequin work and designer blouse. Great for parties. Available in S, M, L, XL. Colors: Navy, Wine, Teal, Emerald, Royal Blue. Fabric: Premium Chiffon with Sequin Work', 3999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 18),
  ('W for Woman Cotton Lehenga Set - Casual', 'W for Woman comfortable cotton lehenga for casual occasions. Available in S, M, L, XL. Colors: White, Grey, Beige, Brown, Olive. Fabric: Pure Cotton', 2499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 25),
  ('Fabindia Silk Lehenga Choli - Premium', 'Fabindia premium silk lehenga with zari work and matching dupatta. Perfect for special occasions. Sizes: S, M, L, XL. Colors: Gold, Silver, Peach, Mint, Lavender. Fabric: Pure Silk with Zari Work', 4999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 14);

-- ============================================
-- 2. MEN'S FASHION (35+ products)
-- Styles: Formal, Casual, Traditional | Brands: Allen Solly, Van Heusen, Arrow, Peter England
-- Price Range: ₹399 - ₹4999 | Sizes: S, M, L, XL, XXL (Shirts/T-shirts), 28-40 (Pants)
-- ============================================
INSERT INTO public.products (name, description, price, category_id, subcategory, image_url, stock) VALUES
  -- Shirts (10 products)
  ('Van Heusen Formal Cotton Shirt - Office Wear', 'Van Heusen premium cotton formal shirt, perfect for office wear. Classic fit with button-down collar. Available in sizes S, M, L, XL, XXL. Colors: White, Light Blue, Grey, Beige. Fabric: Premium Cotton', 1299, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 40),
  ('Allen Solly Casual Checked Shirt - Comfort', 'Allen Solly comfortable casual shirt with checkered pattern. Perfect for smart casual look. Sizes: S, M, L, XL. Colors: Red-Black, Blue-White, Green-Black, Brown-White. Fabric: Soft Cotton', 899, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 50),
  ('Arrow Linen Summer Shirt - Lightweight', 'Arrow lightweight linen shirt, ideal for hot weather. Breathable fabric with modern fit. Available in S, M, L, XL. Colors: White, Beige, Khaki, Light Blue. Fabric: Premium Linen', 1199, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 35),
  ('Peter England Designer Printed Shirt - Modern', 'Peter England stylish designer shirt with modern prints. Contemporary design for fashion-forward men. Sizes: S, M, L, XL. Colors: Navy, Black, Grey, Olive. Fabric: Premium Cotton', 1499, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 30),
  ('Van Heusen Denim Shirt - Classic', 'Van Heusen classic denim shirt for casual occasions. Durable and stylish. Available in S, M, L, XL, XXL. Colors: Light Blue, Dark Blue, Black, Grey. Fabric: Premium Denim', 999, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 45),
  ('Arrow Striped Formal Shirt - Business', 'Arrow elegant striped formal shirt for business meetings. Professional look with quality fabric. Sizes: S, M, L, XL. Colors: Blue-White, Grey-White, Pink-White. Fabric: Premium Cotton', 1399, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 38),
  ('Allen Solly Oxford Cotton Shirt - Versatile', 'Allen Solly premium Oxford cotton shirt, versatile style. Perfect for office and casual wear. Available in S, M, L, XL. Colors: White, Blue, Pink, Yellow. Fabric: Oxford Cotton', 1599, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 32),
  ('Peter England Kurta Shirt - Traditional', 'Peter England traditional kurta style shirt with modern fit. Perfect for festivals and casual wear. Sizes: S, M, L, XL, XXL. Colors: White, Cream, Beige, Light Grey. Fabric: Soft Cotton', 799, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 40),
  ('Van Heusen Polo Shirt - Casual', 'Van Heusen classic polo shirt for casual wear. Comfortable and stylish. Available in S, M, L, XL. Colors: Navy, Black, White, Red, Green. Fabric: Premium Pique Cotton', 699, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 55),
  ('Arrow Long Sleeve Shirt - Formal', 'Arrow long sleeve formal shirt with button-down collar. Professional appearance. Sizes: S, M, L, XL. Colors: White, Light Blue, Grey. Fabric: Premium Cotton', 1699, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 28),
  
  -- T-shirts (10 products)
  ('Allen Solly Cotton Polo T-Shirt - Daily Wear', 'Allen Solly comfortable cotton polo t-shirt for daily wear. Classic design with collar. Available in S, M, L, XL, XXL. Colors: White, Black, Navy, Grey, Red. Fabric: Premium Cotton', 499, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 60),
  ('Van Heusen Graphic Print T-Shirt - Trendy', 'Van Heusen trendy t-shirt with graphic prints and designs. Modern street style. Sizes: S, M, L, XL. Colors: Black, White, Grey, Navy. Fabric: Soft Cotton', 599, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 55),
  ('Peter England V-Neck T-Shirt - Classic', 'Peter England classic V-neck t-shirt in multiple colors. Comfortable fit for casual wear. Available in S, M, L, XL. Colors: Black, White, Grey, Navy, Red, Blue. Fabric: Premium Cotton', 399, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 70),
  ('Arrow Round Neck T-Shirt - Comfort', 'Arrow comfortable round neck t-shirt, perfect for casual wear. Soft fabric with good fit. Sizes: S, M, L, XL, XXL. Colors: White, Black, Grey, Navy. Fabric: Premium Cotton', 449, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 65),
  ('Allen Solly Slim Fit T-Shirt - Modern', 'Allen Solly modern slim fit t-shirt with premium fabric. Contemporary style. Available in S, M, L, XL. Colors: Black, White, Grey, Navy, Olive. Fabric: Premium Cotton', 699, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 50),
  ('Van Heusen Oversized T-Shirt - Street Style', 'Van Heusen trendy oversized t-shirt for street style. Comfortable loose fit. Sizes: S, M, L, XL. Colors: Black, White, Grey, Beige. Fabric: Soft Cotton', 549, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 45),
  ('Peter England Cotton Crew Neck T-Shirt - Basic', 'Peter England classic crew neck t-shirt, comfortable fit. Essential wardrobe piece. Available in S, M, L, XL, XXL. Colors: White, Black, Grey, Navy, Red. Fabric: Premium Cotton', 449, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 60),
  ('Arrow Premium Cotton T-Shirt - Quality', 'Arrow high-quality premium cotton t-shirt. Durable and comfortable. Sizes: S, M, L, XL. Colors: Black, White, Navy, Grey, Olive. Fabric: Premium Cotton', 799, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 40),
  ('Allen Solly Henley T-Shirt - Casual', 'Allen Solly comfortable henley t-shirt with button placket. Stylish casual wear. Available in S, M, L, XL. Colors: Navy, Grey, Black, White. Fabric: Soft Cotton', 649, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 48),
  ('Van Heusen Pocket T-Shirt - Classic', 'Van Heusen classic t-shirt with chest pocket. Functional and stylish. Sizes: S, M, L, XL. Colors: White, Black, Navy, Grey. Fabric: Premium Cotton', 599, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 52),
  
  -- Pants (8 products)
  ('Van Heusen Formal Trousers - Office', 'Van Heusen classic formal trousers for office wear. Professional appearance. Available in sizes 28, 30, 32, 34, 36, 38. Colors: Black, Navy, Grey, Beige. Fabric: Premium Cotton Blend', 1499, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 35),
  ('Allen Solly Slim Fit Jeans - Denim', 'Allen Solly comfortable slim fit denim jeans. Modern fit with stretch. Sizes: 28, 30, 32, 34, 36. Colors: Blue, Black, Grey, Light Blue. Fabric: Premium Denim with Stretch', 1299, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 40),
  ('Arrow Chinos Pants - Smart Casual', 'Arrow versatile chinos pants for smart casual look. Perfect for office and casual wear. Available in 28, 30, 32, 34, 36. Colors: Khaki, Navy, Beige, Olive. Fabric: Premium Cotton Chino', 1199, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 38),
  ('Peter England Cargo Pants - Practical', 'Peter England practical cargo pants with multiple pockets. Functional design. Sizes: 30, 32, 34, 36, 38. Colors: Black, Khaki, Olive, Grey. Fabric: Durable Cotton Blend', 999, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 42),
  ('Van Heusen Straight Fit Jeans - Classic', 'Van Heusen classic straight fit jeans for everyday wear. Comfortable traditional fit. Available in 28, 30, 32, 34, 36, 38. Colors: Blue, Black, Grey. Fabric: Premium Denim', 1099, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 45),
  ('Allen Solly Cotton Trousers - Casual', 'Allen Solly comfortable cotton trousers for casual occasions. Relaxed fit. Sizes: 30, 32, 34, 36. Colors: Beige, Khaki, Grey, Navy. Fabric: Soft Cotton', 899, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 40),
  ('Arrow Linen Pants - Summer', 'Arrow lightweight linen pants for summer. Breathable and comfortable. Available in 30, 32, 34, 36. Colors: White, Beige, Khaki, Light Blue. Fabric: Premium Linen', 1299, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 35),
  ('Peter England Jogger Pants - Active', 'Peter England comfortable jogger pants for active lifestyle. Modern tapered fit. Sizes: S, M, L, XL. Colors: Black, Grey, Navy, Olive. Fabric: Soft Cotton Blend', 799, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 50),
  
  -- Belts (3 products)
  ('Van Heusen Leather Formal Belt - Premium', 'Van Heusen premium leather belt for formal wear. Durable and stylish. Available in sizes 32, 34, 36, 38, 40 inches. Colors: Black, Brown, Tan. Material: Genuine Leather', 699, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Belts', 'https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=800', 40),
  ('Allen Solly Casual Canvas Belt - Stylish', 'Allen Solly stylish canvas belt for casual outfits. Modern design. Sizes: 30, 32, 34, 36, 38 inches. Colors: Black, Brown, Navy, Grey. Material: Durable Canvas', 399, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Belts', 'https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=800', 50),
  ('Arrow Reversible Belt - Versatile', 'Arrow versatile reversible belt with two colors. Two belts in one. Available in 32, 34, 36, 38 inches. Color combinations: Black-Brown, Brown-Tan. Material: Genuine Leather', 599, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Belts', 'https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=800', 35),
  
  -- Watches (2 products)
  ('Titan Analog Watch - Classic', 'Titan classic analog watch with leather strap. Elegant timepiece. Available in multiple dial colors: Black, Silver, Gold, Blue. Material: Stainless Steel Case, Leather Strap', 1999, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Watches', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', 25),
  ('Fastrack Digital Sports Watch - Feature Rich', 'Fastrack feature-rich digital sports watch with multiple functions. Perfect for fitness enthusiasts. Colors: Black, Blue, Red, Green. Material: Resin Case, Silicone Strap', 2499, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Watches', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', 20),
  
  -- Footwear (2 products)
  ('Bata Formal Leather Shoes - Premium', 'Bata premium leather formal shoes. Classic design for office wear. Available in sizes 7, 8, 9, 10, 11. Colors: Black, Brown, Tan. Material: Genuine Leather', 2999, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Footwear', 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800', 20),
  ('Nike Casual Sneakers - Comfort', 'Nike comfortable casual sneakers for daily wear. Cushioned sole for all-day comfort. Sizes: 7-11. Colors: White, Black, Navy, Grey. Material: Synthetic Upper, Rubber Sole', 1999, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Footwear', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', 30);

-- Continue with remaining categories...

