-- Migration: Enhanced Product Data with Detailed Specifications
-- This migration replaces existing products with enhanced data including:
-- - Specific styles, fabrics, and designs
-- - Indian brand names
-- - Size variations (S, M, L, XL) where applicable
-- - Detailed product descriptions
-- All prices are in Indian Rupees (INR)

-- First, delete existing products (to avoid foreign key issues)
DELETE FROM public.products;

-- ============================================
-- 1. KURTIS, SAREES & LEHENGAS (35+ products)
-- Price Range: ₹299 - ₹4999
-- ============================================
INSERT INTO public.products (name, description, price, category_id, subcategory, image_url, stock) VALUES
  -- Kurtis - Anarkali Style (8 products)
  ('Fabindia Anarkali Cotton Kurti', 'Elegant Anarkali style kurti by Fabindia. Pure cotton fabric with traditional Indian prints. Flared silhouette perfect for parties. Sizes: S, M, L, XL. Colors: Red, Blue, Green, Yellow, Pink. Price: ₹599', 599, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 45),
  ('W Anarkali Silk Kurti', 'Premium Anarkali kurti by W in pure silk fabric. Intricate zari embroidery work. Perfect for weddings and special occasions. Sizes: S, M, L, XL. Colors: Maroon, Navy, Gold, Purple. Price: ₹2499', 2499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 25),
  ('Biba Anarkali Chiffon Kurti', 'Stylish Anarkali kurti by Biba in chiffon fabric. Modern prints with sequin work. Great for parties. Sizes: S, M, L, XL. Colors: Black, Royal Blue, Wine, Emerald. Price: ₹1899', 1899, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 30),
  ('Manyavar Anarkali Georgette Kurti', 'Elegant Anarkali kurti by Manyavar in georgette fabric. Floral embroidery with mirror work. Sizes: S, M, L, XL. Colors: Peach, Mint, Lavender, Coral. Price: ₹1299', 1299, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 35),
  ('Allen Solly Anarkali Rayon Kurti', 'Comfortable Anarkali kurti by Allen Solly in rayon fabric. Lightweight and perfect for summer. Sizes: S, M, L, XL. Colors: White, Sky Blue, Lavender, Coral. Price: ₹799', 799, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 40),
  ('Global Desi Anarkali Cotton Kurti', 'Casual Anarkali kurti by Global Desi in pure cotton. Block prints with modern designs. Sizes: S, M, L, XL. Colors: Orange, Magenta, Cyan, Mustard. Price: ₹699', 699, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 50),
  ('Soch Anarkali Linen Kurti', 'Premium Anarkali kurti by Soch in linen fabric. Delicate embroidery work. Breathable and comfortable. Sizes: S, M, L, XL. Colors: Cream, Khaki, Terracotta, Sage. Price: ₹1499', 1499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 28),
  ('Indya Anarkali Silk Kurti', 'Luxury Anarkali kurti by Indya in pure silk. Handcrafted embroidery with zari work. Sizes: S, M, L, XL. Colors: Gold, Silver, Peach, Mint. Price: ₹2999', 2999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 22),
  
  -- Kurtis - A-Line Style (8 products)
  ('Fabindia A-Line Cotton Kurti', 'Classic A-line kurti by Fabindia in pure cotton. Comfortable fit with side slits. Perfect for daily wear. Sizes: S, M, L, XL. Colors: Red, Blue, Green, Yellow. Price: ₹499', 499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 55),
  ('W A-Line Silk Kurti', 'Elegant A-line kurti by W in pure silk. Traditional prints with modern fit. Sizes: S, M, L, XL. Colors: Maroon, Navy, Teal, Purple. Price: ₹2199', 2199, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 30),
  ('Biba A-Line Chiffon Kurti', 'Stylish A-line kurti by Biba in chiffon fabric. Floral prints with sequin accents. Sizes: S, M, L, XL. Colors: Black, Navy, Wine, Emerald. Price: ₹1599', 1599, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 32),
  ('Manyavar A-Line Georgette Kurti', 'Elegant A-line kurti by Manyavar in georgette. Embroidered borders with mirror work. Sizes: S, M, L, XL. Colors: Grey, Beige, Rose, Turquoise. Price: ₹999', 999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 42),
  ('Allen Solly A-Line Rayon Kurti', 'Comfortable A-line kurti by Allen Solly in rayon. Lightweight fabric perfect for summer. Sizes: S, M, L, XL. Colors: White, Sky Blue, Lavender, Coral. Price: ₹699', 699, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 48),
  ('Global Desi A-Line Cotton Kurti', 'Casual A-line kurti by Global Desi in cotton. Block prints with contemporary designs. Sizes: S, M, L, XL. Colors: Orange, Magenta, Cyan, Mustard. Price: ₹599', 599, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 52),
  ('Soch A-Line Linen Kurti', 'Premium A-line kurti by Soch in linen. Delicate embroidery with traditional motifs. Sizes: S, M, L, XL. Colors: Cream, Khaki, Terracotta, Sage. Price: ₹1299', 1299, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 35),
  ('Indya A-Line Silk Kurti', 'Luxury A-line kurti by Indya in pure silk. Handcrafted zari work. Perfect for special occasions. Sizes: S, M, L, XL. Colors: Gold, Silver, Peach, Mint. Price: ₹2499', 2499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 25),
  
  -- Kurtis - Straight Style (8 products)
  ('Fabindia Straight Cotton Kurti', 'Classic straight cut kurti by Fabindia in pure cotton. Simple and elegant for office wear. Sizes: S, M, L, XL. Colors: White, Black, Brown, Olive. Price: ₹399', 399, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 60),
  ('W Straight Silk Kurti', 'Elegant straight kurti by W in pure silk. Formal design perfect for office. Sizes: S, M, L, XL. Colors: Burgundy, Charcoal, Ivory, Plum. Price: ₹1999', 1999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 28),
  ('Biba Straight Chiffon Kurti', 'Stylish straight kurti by Biba in chiffon. Modern prints with comfortable fit. Sizes: S, M, L, XL. Colors: Navy, Wine, Teal, Gold. Price: ₹1399', 1399, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 38),
  ('Manyavar Straight Georgette Kurti', 'Elegant straight kurti by Manyavar in georgette. Subtle embroidery work. Sizes: S, M, L, XL. Colors: Grey, Beige, Rose, Turquoise. Price: ₹899', 899, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 45),
  ('Allen Solly Straight Rayon Kurti', 'Comfortable straight kurti by Allen Solly in rayon. Lightweight and breathable. Sizes: S, M, L, XL. Colors: White, Sky Blue, Lavender, Coral. Price: ₹599', 599, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 50),
  ('Global Desi Straight Cotton Kurti', 'Casual straight kurti by Global Desi in cotton. Contemporary prints. Sizes: S, M, L, XL. Colors: Indigo, Rust, Mint, Peach. Price: ₹499', 499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 55),
  ('Soch Straight Linen Kurti', 'Premium straight kurti by Soch in linen. Minimalist design with delicate work. Sizes: S, M, L, XL. Colors: Cream, Khaki, Terracotta, Sage. Price: ₹1199', 1199, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 40),
  ('Indya Straight Silk Kurti', 'Luxury straight kurti by Indya in pure silk. Premium quality with zari borders. Sizes: S, M, L, XL. Colors: Gold, Silver, Peach, Mint. Price: ₹2299', 2299, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 30),
  
  -- Sarees (8 products)
  ('Fabindia Cotton Handloom Saree', 'Traditional handloom cotton saree by Fabindia. Beautiful border work with traditional motifs. Colors: Red, Green, Blue, Yellow, Orange. Price: ₹1999', 1999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1594633312681-425c7b7ccd1?w=800', 20),
  ('W Silk Kanjivaram Saree', 'Authentic Kanjivaram silk saree by W. Premium zari work with traditional designs. Colors: Maroon, Green, Gold, Blue, Purple. Price: ₹8999', 8999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 10),
  ('Biba Georgette Designer Saree', 'Elegant georgette saree by Biba with designer blouse. Perfect for weddings. Colors: Pink, Peach, Mint, Lavender, Coral. Price: ₹3499', 3499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 15),
  ('Manyavar Chiffon Party Saree', 'Stylish chiffon saree by Manyavar with sequin and stone work. Colors: Black, Navy, Wine, Emerald, Royal Blue. Price: ₹2499', 2499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 18),
  ('Soch Silk Banarasi Saree', 'Traditional Banarasi silk saree by Soch. Intricate brocade work. Colors: Red, Green, Gold, Blue, Maroon. Price: ₹6999', 6999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 12),
  ('Indya Organza Embroidered Saree', 'Luxurious organza saree by Indya with hand embroidery. Perfect for special occasions. Colors: Ivory, Peach, Mint, Lavender. Price: ₹4999', 4999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 14),
  ('Fabindia Linen Handloom Saree', 'Elegant linen handloom saree by Fabindia. Traditional motifs with modern appeal. Colors: Cream, Khaki, Terracotta, Sage, Beige. Price: ₹2999', 2999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 20),
  ('W Cotton Jamdani Saree', 'Artisan-made Jamdani cotton saree by W. Intricate patterns. Colors: Indigo, Rust, Mint, Peach, Coral. Price: ₹2299', 2299, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 17),
  
  -- Lehengas (6 products)
  ('Biba Designer Lehenga Choli', 'Beautiful lehenga choli set by Biba with intricate embroidery and dupatta. Sizes: S, M, L, XL. Colors: Red, Pink, Blue, Green, Purple. Price: ₹5999', 5999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 12),
  ('Manyavar Bridal Lehenga Set', 'Stunning bridal lehenga by Manyavar with heavy work. Perfect for weddings. Sizes: S, M, L, XL. Colors: Red, Maroon, Gold, Pink, Peach. Price: ₹12999', 12999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 8),
  ('Soch Party Lehenga Choli', 'Elegant party lehenga by Soch with sequin work and designer blouse. Sizes: S, M, L, XL. Colors: Navy, Wine, Teal, Emerald, Royal Blue. Price: ₹4499', 4499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 15),
  ('Indya Silk Lehenga Choli', 'Premium silk lehenga by Indya with zari work and matching dupatta. Sizes: S, M, L, XL. Colors: Gold, Silver, Peach, Mint, Lavender. Price: ₹7999', 7999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 10),
  ('Fabindia Cotton Lehenga Set', 'Comfortable cotton lehenga by Fabindia for casual occasions. Sizes: S, M, L, XL. Colors: White, Grey, Beige, Brown, Olive. Price: ₹2499', 2499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 20),
  ('W Georgette Lehenga Set', 'Stylish georgette lehenga by W with modern design. Sizes: S, M, L, XL. Colors: Coral, Rose, Turquoise, Grey, Beige. Price: ₹3499', 3499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 18),
  
  -- Blouses (3 products)
  ('Biba Designer Blouse', 'Elegant designer blouse by Biba with embroidery work. Sizes: S, M, L, XL. Colors: Red, Blue, Green, Yellow, Pink. Price: ₹1299', 1299, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Blouses', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 30),
  ('Soch Silk Embroidered Blouse', 'Premium silk blouse by Soch with handcrafted embroidery. Sizes: S, M, L, XL. Colors: Maroon, Navy, Teal, Purple, Gold. Price: ₹1999', 1999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Blouses', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 25),
  ('Fabindia Cotton Casual Blouse', 'Comfortable cotton blouse by Fabindia for daily wear. Sizes: S, M, L, XL. Colors: White, Black, Brown, Olive, Grey. Price: ₹599', 599, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Blouses', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 40),
  
  -- Dupattas (2 products)
  ('Biba Printed Dupatta', 'Beautiful printed dupatta by Biba with vibrant colors. Colors: Red, Blue, Green, Yellow, Pink, Orange. Price: ₹399', 399, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Dupattas', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 50),
  ('Soch Embroidered Dupatta', 'Elegant embroidered dupatta by Soch with intricate work. Colors: Maroon, Navy, Teal, Purple, Gold, Silver. Price: ₹799', 799, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Dupattas', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 35);

-- ============================================
-- 2. MEN'S FASHION (35+ products)
-- Price Range: ₹399 - ₹4999
-- ============================================
INSERT INTO public.products (name, description, price, category_id, subcategory, image_url, stock) VALUES
  -- Shirts - Formal Style (8 products)
  ('Van Heusen Formal Cotton Shirt', 'Premium formal cotton shirt by Van Heusen. Perfect for office wear. Sizes: S, M, L, XL, XXL. Colors: White, Light Blue, Grey, Beige. Price: ₹1299', 1299, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 40),
  ('Arrow Formal Oxford Shirt', 'Classic Oxford cotton shirt by Arrow. Versatile style for business meetings. Sizes: S, M, L, XL. Colors: White, Blue, Pink, Yellow. Price: ₹1599', 1599, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 32),
  ('Allen Solly Striped Formal Shirt', 'Elegant striped formal shirt by Allen Solly. Perfect for business meetings. Sizes: S, M, L, XL. Colors: Blue-White, Grey-White, Pink-White. Price: ₹1399', 1399, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 38),
  ('Peter England Long Sleeve Shirt', 'Long sleeve formal shirt by Peter England with button-down collar. Sizes: S, M, L, XL. Colors: White, Light Blue, Grey. Price: ₹1699', 1699, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 28),
  ('Louis Philippe Premium Cotton Shirt', 'Premium cotton formal shirt by Louis Philippe. Office wear essential. Sizes: S, M, L, XL, XXL. Colors: White, Light Blue, Grey, Beige. Price: ₹1999', 1999, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 30),
  ('Park Avenue Linen Summer Shirt', 'Lightweight linen shirt by Park Avenue. Ideal for hot weather. Sizes: S, M, L, XL. Colors: White, Beige, Khaki, Light Blue. Price: ₹1199', 1199, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 35),
  ('Blackberry Designer Printed Shirt', 'Stylish designer shirt by Blackberry with modern prints. Sizes: S, M, L, XL. Colors: Navy, Black, Grey, Olive. Price: ₹1499', 1499, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 30),
  ('U.S. Polo Assn. Polo Shirt', 'Classic polo shirt by U.S. Polo Assn. for casual wear. Sizes: S, M, L, XL. Colors: Navy, Black, White, Red, Green. Price: ₹699', 699, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 55),
  
  -- Shirts - Casual Style (7 products)
  ('Levi''s Denim Shirt', 'Classic denim shirt by Levi''s for casual occasions. Sizes: S, M, L, XL, XXL. Colors: Light Blue, Dark Blue, Black, Grey. Price: ₹999', 999, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 45),
  ('H&M Casual Checked Shirt', 'Comfortable casual shirt by H&M with checkered pattern. Sizes: S, M, L, XL. Colors: Red-Black, Blue-White, Green-Black, Brown-White. Price: ₹899', 899, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 50),
  ('Flying Machine Kurta Shirt', 'Traditional kurta style shirt by Flying Machine with modern fit. Sizes: S, M, L, XL, XXL. Colors: White, Cream, Beige, Light Grey. Price: ₹799', 799, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 40),
  ('Mufti Casual Linen Shirt', 'Comfortable casual linen shirt by Mufti. Perfect for summer. Sizes: S, M, L, XL. Colors: White, Beige, Khaki, Light Blue. Price: ₹1099', 1099, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 38),
  ('Wrangler Flannel Shirt', 'Warm flannel shirt by Wrangler. Perfect for winter. Sizes: S, M, L, XL. Colors: Red-Black, Blue-White, Green-Black. Price: ₹1199', 1199, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 35),
  ('Pepe Jeans Casual Shirt', 'Stylish casual shirt by Pepe Jeans. Modern designs. Sizes: S, M, L, XL. Colors: Navy, Black, Grey, Olive. Price: ₹999', 999, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 42),
  ('UCB Casual Printed Shirt', 'Trendy printed casual shirt by UCB. Contemporary designs. Sizes: S, M, L, XL. Colors: Navy, Black, Grey, Olive. Price: ₹1299', 1299, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 33),
  
  -- T-shirts (10 products)
  ('Puma Cotton Polo T-Shirt', 'Comfortable cotton polo t-shirt by Puma for daily wear. Sizes: S, M, L, XL, XXL. Colors: White, Black, Navy, Grey, Red. Price: ₹499', 499, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 60),
  ('Nike Graphic Print T-Shirt', 'Trendy t-shirt by Nike with graphic prints and designs. Sizes: S, M, L, XL. Colors: Black, White, Grey, Navy. Price: ₹599', 599, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 55),
  ('Adidas V-Neck T-Shirt', 'Classic V-neck t-shirt by Adidas in multiple colors. Sizes: S, M, L, XL. Colors: Black, White, Grey, Navy, Red, Blue. Price: ₹399', 399, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 70),
  ('Reebok Round Neck T-Shirt', 'Comfortable round neck t-shirt by Reebok. Perfect for casual wear. Sizes: S, M, L, XL, XXL. Colors: White, Black, Grey, Navy. Price: ₹449', 449, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 65),
  ('Under Armour Slim Fit T-Shirt', 'Modern slim fit t-shirt by Under Armour with premium fabric. Sizes: S, M, L, XL. Colors: Black, White, Grey, Navy, Olive. Price: ₹699', 699, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 50),
  ('Levi''s Oversized T-Shirt', 'Trendy oversized t-shirt by Levi''s for street style. Sizes: S, M, L, XL. Colors: Black, White, Grey, Beige. Price: ₹549', 549, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 45),
  ('H&M Cotton Crew Neck T-Shirt', 'Classic crew neck t-shirt by H&M. Comfortable fit. Sizes: S, M, L, XL, XXL. Colors: White, Black, Grey, Navy, Red. Price: ₹449', 449, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 60),
  ('Zara Premium Cotton T-Shirt', 'High-quality premium cotton t-shirt by Zara. Sizes: S, M, L, XL. Colors: Black, White, Navy, Grey, Olive. Price: ₹799', 799, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 40),
  ('UCB Henley T-Shirt', 'Comfortable henley t-shirt by UCB with button placket. Sizes: S, M, L, XL. Colors: Navy, Grey, Black, White. Price: ₹649', 649, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 48),
  ('Gap Pocket T-Shirt', 'Classic t-shirt by Gap with chest pocket. Sizes: S, M, L, XL. Colors: White, Black, Navy, Grey. Price: ₹599', 599, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 52),
  
  -- Pants (8 products)
  ('Van Heusen Formal Trousers', 'Classic formal trousers by Van Heusen for office wear. Sizes: 28, 30, 32, 34, 36, 38. Colors: Black, Navy, Grey, Beige. Price: ₹1499', 1499, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 35),
  ('Levi''s Slim Fit Jeans', 'Comfortable slim fit denim jeans by Levi''s. Sizes: 28, 30, 32, 34, 36. Colors: Blue, Black, Grey, Light Blue. Price: ₹1299', 1299, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 40),
  ('Arrow Chinos Pants', 'Versatile chinos pants by Arrow for smart casual look. Sizes: 28, 30, 32, 34, 36. Colors: Khaki, Navy, Beige, Olive. Price: ₹1199', 1199, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 38),
  ('Wrangler Cargo Pants', 'Practical cargo pants by Wrangler with multiple pockets. Sizes: 30, 32, 34, 36, 38. Colors: Black, Khaki, Olive, Grey. Price: ₹999', 999, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 42),
  ('Pepe Jeans Straight Fit Jeans', 'Classic straight fit jeans by Pepe Jeans for everyday wear. Sizes: 28, 30, 32, 34, 36, 38. Colors: Blue, Black, Grey. Price: ₹1099', 1099, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 45),
  ('Allen Solly Cotton Trousers', 'Comfortable cotton trousers by Allen Solly for casual occasions. Sizes: 30, 32, 34, 36. Colors: Beige, Khaki, Grey, Navy. Price: ₹899', 899, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 40),
  ('Park Avenue Linen Pants', 'Lightweight linen pants by Park Avenue for summer. Sizes: 30, 32, 34, 36. Colors: White, Beige, Khaki, Light Blue. Price: ₹1299', 1299, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 35),
  ('Puma Jogger Pants', 'Comfortable jogger pants by Puma for active lifestyle. Sizes: S, M, L, XL. Colors: Black, Grey, Navy, Olive. Price: ₹799', 799, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 50),
  
  -- Belts (2 products)
  ('Hidesign Leather Formal Belt', 'Premium leather belt by Hidesign for formal wear. Sizes: 32, 34, 36, 38, 40 inches. Colors: Black, Brown, Tan. Price: ₹699', 699, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Belts', 'https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=800', 40),
  ('Fastrack Casual Canvas Belt', 'Stylish canvas belt by Fastrack for casual outfits. Sizes: 30, 32, 34, 36, 38 inches. Colors: Black, Brown, Navy, Grey. Price: ₹399', 399, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Belts', 'https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=800', 50);

-- Continue with remaining categories in next section...

