-- Migration: Complete Product Data for All Categories
-- This migration adds comprehensive product data (30+ products per category)
-- All prices are in Indian Rupees (INR)
-- Product variations (sizes, colors) are included in descriptions

-- First, delete existing products (to avoid foreign key issues)
DELETE FROM public.products;

-- Ensure categories exist (run category migration first if needed)
-- Categories should already exist from previous migration

-- ============================================
-- 1. KURTIS, SAREES & LEHENGAS (35 products)
-- ============================================
INSERT INTO public.products (name, description, price, category_id, subcategory, image_url, stock) VALUES
  -- Kurtis (12 products)
  ('Cotton Printed Kurti - Multi Color', 'Comfortable cotton kurti with beautiful Indian prints. Available in sizes S, M, L, XL. Colors: Red, Blue, Green, Yellow, Pink. Perfect for daily wear', 599, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 50),
  ('Designer Anarkali Kurti - Embroidered', 'Elegant anarkali style kurti with intricate embroidery work. Sizes: S, M, L, XL. Colors: Maroon, Navy, Teal, Purple. Perfect for parties', 1299, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 30),
  ('Silk Embroidered Kurti - Premium', 'Premium silk kurti with handcrafted embroidery. Available in S, M, L, XL. Colors: Gold, Silver, Peach, Mint. Ideal for special occasions', 2499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 25),
  ('Rayon Floral Kurti - Summer Collection', 'Lightweight rayon kurti with floral patterns. Sizes: S, M, L, XL. Colors: White, Sky Blue, Lavender, Coral. Perfect for summer', 799, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 40),
  ('Chiffon Party Kurti - Sequin Work', 'Stylish chiffon kurti with sequin work. Available in S, M, L, XL. Colors: Black, Royal Blue, Wine, Emerald. Great for parties', 1899, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 35),
  ('Georgette Printed Kurti - Modern', 'Elegant georgette kurti with modern prints. Sizes: S, M, L, XL. Colors: Grey, Beige, Rose, Turquoise. Comfortable fit', 999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 45),
  ('Cotton Casual Kurti - Everyday', 'Simple and comfortable cotton kurti. Available in S, M, L, XL. Colors: White, Black, Brown, Olive. For everyday wear', 499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 60),
  ('Linen Embroidered Kurti - Breathable', 'Premium linen kurti with delicate embroidery. Sizes: S, M, L, XL. Colors: Cream, Khaki, Terracotta, Sage. Breathable fabric', 1499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 30),
  ('Cotton A-Line Kurti - Comfort Fit', 'Comfortable A-line cotton kurti with side slits. Available in S, M, L, XL. Colors: Orange, Magenta, Cyan, Mustard', 699, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 55),
  ('Silk Straight Kurti - Formal', 'Elegant straight cut silk kurti. Sizes: S, M, L, XL. Colors: Burgundy, Charcoal, Ivory, Plum. Perfect for office wear', 2199, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 28),
  ('Cotton Long Kurti - Maxi', 'Long maxi cotton kurti with beautiful prints. Available in S, M, L, XL. Colors: Indigo, Rust, Mint, Peach', 899, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 42),
  ('Chiffon Designer Kurti - Party', 'Designer chiffon kurti with mirror work. Sizes: S, M, L, XL. Colors: Navy, Wine, Teal, Gold. For special occasions', 2299, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Kurtis', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 22),
  
  -- Sarees (12 products)
  ('Cotton Handloom Saree - Traditional', 'Traditional handloom cotton saree with beautiful border work. Available in multiple colors: Red, Green, Blue, Yellow, Orange', 1999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1594633312681-425c7b7ccd1?w=800', 20),
  ('Silk Kanjivaram Saree - Authentic', 'Authentic Kanjivaram silk saree with zari work. Premium quality. Colors: Maroon, Green, Gold, Blue, Purple', 8999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 10),
  ('Georgette Designer Saree - Wedding', 'Elegant georgette saree with designer blouse. Perfect for weddings. Colors: Pink, Peach, Mint, Lavender, Coral', 3499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 15),
  ('Chiffon Party Saree - Sequin', 'Stylish chiffon saree with sequin and stone work. Colors: Black, Navy, Wine, Emerald, Royal Blue', 2499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 18),
  ('Cotton Printed Saree - Modern', 'Comfortable cotton saree with modern prints. Ideal for daily wear. Colors: White, Grey, Beige, Brown, Olive', 1299, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 25),
  ('Silk Banarasi Saree - Brocade', 'Traditional Banarasi silk saree with intricate brocade work. Colors: Red, Green, Gold, Blue, Maroon', 6999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 12),
  ('Organza Embroidered Saree - Luxury', 'Luxurious organza saree with hand embroidery. Perfect for special occasions. Colors: Ivory, Peach, Mint, Lavender', 4999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 14),
  ('Linen Handloom Saree - Traditional', 'Elegant linen handloom saree with traditional motifs. Colors: Cream, Khaki, Terracotta, Sage, Beige', 2999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 20),
  ('Cotton Tussar Saree - Handwoven', 'Beautiful handwoven Tussar cotton saree. Colors: Orange, Magenta, Cyan, Mustard, Rust', 1799, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 22),
  ('Silk Mysore Saree - Classic', 'Classic Mysore silk saree with traditional designs. Colors: Burgundy, Charcoal, Ivory, Plum, Navy', 5999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 16),
  ('Chiffon Designer Saree - Party', 'Designer chiffon saree with mirror and sequin work. Colors: Teal, Gold, Silver, Rose, Turquoise', 2799, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 19),
  ('Cotton Jamdani Saree - Artisan', 'Artisan-made Jamdani cotton saree with intricate patterns. Colors: Indigo, Rust, Mint, Peach, Coral', 2299, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Sarees', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 17),
  
  -- Lehengas (8 products)
  ('Designer Lehenga Choli - Embroidered', 'Beautiful lehenga choli set with intricate embroidery and dupatta. Available in sizes S, M, L, XL. Colors: Red, Pink, Blue, Green, Purple', 5999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 12),
  ('Bridal Lehenga Set - Heavy Work', 'Stunning bridal lehenga with heavy work. Perfect for weddings. Sizes: S, M, L, XL. Colors: Red, Maroon, Gold, Pink, Peach', 12999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 8),
  ('Party Lehenga Choli - Sequin', 'Elegant party lehenga with sequin work and designer blouse. Sizes: S, M, L, XL. Colors: Navy, Wine, Teal, Emerald, Royal Blue', 4499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 15),
  ('Cotton Lehenga Set - Casual', 'Comfortable cotton lehenga for casual occasions. Available in S, M, L, XL. Colors: White, Grey, Beige, Brown, Olive', 2499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 20),
  ('Silk Lehenga Choli - Premium', 'Premium silk lehenga with zari work and matching dupatta. Sizes: S, M, L, XL. Colors: Gold, Silver, Peach, Mint, Lavender', 7999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 10),
  ('Georgette Lehenga Set - Modern', 'Stylish georgette lehenga with modern design. Available in S, M, L, XL. Colors: Coral, Rose, Turquoise, Grey, Beige', 3499, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 18),
  ('Chiffon Lehenga Choli - Designer', 'Designer chiffon lehenga with mirror work. Sizes: S, M, L, XL. Colors: Black, Navy, Wine, Emerald, Royal Blue', 5299, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 14),
  ('Cotton A-Line Lehenga - Comfort', 'Comfortable A-line cotton lehenga set. Available in S, M, L, XL. Colors: Orange, Magenta, Cyan, Mustard, Rust', 1999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Lehengas', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 25),
  
  -- Blouses (3 products)
  ('Designer Blouse - Embroidered', 'Elegant designer blouse with embroidery work. Available in sizes S, M, L, XL. Colors: Red, Blue, Green, Yellow, Pink', 1299, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Blouses', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 30),
  ('Silk Embroidered Blouse - Premium', 'Premium silk blouse with handcrafted embroidery. Sizes: S, M, L, XL. Colors: Maroon, Navy, Teal, Purple, Gold', 1999, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Blouses', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 25),
  ('Cotton Casual Blouse - Daily Wear', 'Comfortable cotton blouse for daily wear. Available in S, M, L, XL. Colors: White, Black, Brown, Olive, Grey', 599, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Blouses', 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800', 40),
  
  -- Dupattas (5 products)
  ('Printed Dupatta - Vibrant', 'Beautiful printed dupatta with vibrant colors. Available in multiple color options: Red, Blue, Green, Yellow, Pink, Orange', 399, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Dupattas', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 50),
  ('Embroidered Dupatta - Intricate', 'Elegant embroidered dupatta with intricate work. Colors: Maroon, Navy, Teal, Purple, Gold, Silver', 799, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Dupattas', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 35),
  ('Silk Dupatta - Zari Border', 'Premium silk dupatta with zari border. Available in: Peach, Mint, Lavender, Coral, Rose, Turquoise', 1299, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Dupattas', 'https://images.unsplash.com/photo-1594633313593-bab3825d0caf?w=800', 30),
  ('Chiffon Dupatta - Designer', 'Designer chiffon dupatta with mirror work. Colors: Black, Navy, Wine, Emerald, Royal Blue, Teal', 899, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Dupattas', 'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800', 40),
  ('Cotton Handloom Dupatta - Traditional', 'Traditional handloom cotton dupatta. Colors: White, Grey, Beige, Brown, Olive, Cream', 599, (SELECT id FROM categories WHERE slug = 'kurtis-sarees-lehengas'), 'Dupattas', 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800', 45);

-- ============================================
-- 2. MEN'S FASHION (35 products)
-- ============================================
INSERT INTO public.products (name, description, price, category_id, subcategory, image_url, stock) VALUES
  -- Shirts (10 products)
  ('Formal Cotton Shirt - Office Wear', 'Premium cotton formal shirt, perfect for office wear. Sizes: S, M, L, XL, XXL. Colors: White, Light Blue, Grey, Beige', 1299, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 40),
  ('Casual Checked Shirt - Comfort', 'Comfortable casual shirt with checkered pattern. Available in S, M, L, XL. Colors: Red-Black, Blue-White, Green-Black, Brown-White', 899, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 50),
  ('Linen Summer Shirt - Lightweight', 'Lightweight linen shirt, ideal for hot weather. Sizes: S, M, L, XL. Colors: White, Beige, Khaki, Light Blue', 1199, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 35),
  ('Designer Printed Shirt - Modern', 'Stylish designer shirt with modern prints. Available in S, M, L, XL. Colors: Navy, Black, Grey, Olive', 1499, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 30),
  ('Denim Shirt - Classic', 'Classic denim shirt for casual occasions. Sizes: S, M, L, XL, XXL. Colors: Light Blue, Dark Blue, Black, Grey', 999, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 45),
  ('Striped Formal Shirt - Business', 'Elegant striped formal shirt for business meetings. Available in S, M, L, XL. Colors: Blue-White, Grey-White, Pink-White', 1399, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 38),
  ('Oxford Cotton Shirt - Versatile', 'Premium Oxford cotton shirt, versatile style. Sizes: S, M, L, XL. Colors: White, Blue, Pink, Yellow', 1599, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 32),
  ('Kurta Shirt - Traditional', 'Traditional kurta style shirt with modern fit. Available in S, M, L, XL, XXL. Colors: White, Cream, Beige, Light Grey', 799, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 40),
  ('Polo Shirt - Casual', 'Classic polo shirt for casual wear. Sizes: S, M, L, XL. Colors: Navy, Black, White, Red, Green', 699, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1602810318660-d2c46b750f88?w=800', 55),
  ('Long Sleeve Shirt - Formal', 'Long sleeve formal shirt with button-down collar. Available in S, M, L, XL. Colors: White, Light Blue, Grey', 1699, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Shirts', 'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800', 28),
  
  -- T-shirts (10 products)
  ('Cotton Polo T-Shirt - Daily Wear', 'Comfortable cotton polo t-shirt for daily wear. Sizes: S, M, L, XL, XXL. Colors: White, Black, Navy, Grey, Red', 499, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 60),
  ('Graphic Print T-Shirt - Trendy', 'Trendy t-shirt with graphic prints and designs. Available in S, M, L, XL. Colors: Black, White, Grey, Navy', 599, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 55),
  ('V-Neck T-Shirt - Classic', 'Classic V-neck t-shirt in multiple colors. Sizes: S, M, L, XL. Colors: Black, White, Grey, Navy, Red, Blue', 399, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 70),
  ('Round Neck T-Shirt - Comfort', 'Comfortable round neck t-shirt, perfect for casual wear. Available in S, M, L, XL, XXL. Colors: White, Black, Grey, Navy', 449, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 65),
  ('Slim Fit T-Shirt - Modern', 'Modern slim fit t-shirt with premium fabric. Sizes: S, M, L, XL. Colors: Black, White, Grey, Navy, Olive', 699, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 50),
  ('Oversized T-Shirt - Street Style', 'Trendy oversized t-shirt for street style. Available in S, M, L, XL. Colors: Black, White, Grey, Beige', 549, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 45),
  ('Cotton Crew Neck T-Shirt - Basic', 'Classic crew neck t-shirt, comfortable fit. Sizes: S, M, L, XL, XXL. Colors: White, Black, Grey, Navy, Red', 449, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 60),
  ('Premium Cotton T-Shirt - Quality', 'High-quality premium cotton t-shirt. Available in S, M, L, XL. Colors: Black, White, Navy, Grey, Olive', 799, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 40),
  ('Henley T-Shirt - Casual', 'Comfortable henley t-shirt with button placket. Sizes: S, M, L, XL. Colors: Navy, Grey, Black, White', 649, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 48),
  ('Pocket T-Shirt - Classic', 'Classic t-shirt with chest pocket. Available in S, M, L, XL. Colors: White, Black, Navy, Grey', 599, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'T-shirts', 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', 52),
  
  -- Pants (8 products)
  ('Formal Trousers - Office', 'Classic formal trousers for office wear. Sizes: 28, 30, 32, 34, 36, 38. Colors: Black, Navy, Grey, Beige', 1499, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 35),
  ('Slim Fit Jeans - Denim', 'Comfortable slim fit denim jeans. Available in 28, 30, 32, 34, 36. Colors: Blue, Black, Grey, Light Blue', 1299, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 40),
  ('Chinos Pants - Smart Casual', 'Versatile chinos pants for smart casual look. Sizes: 28, 30, 32, 34, 36. Colors: Khaki, Navy, Beige, Olive', 1199, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 38),
  ('Cargo Pants - Practical', 'Practical cargo pants with multiple pockets. Available in 30, 32, 34, 36, 38. Colors: Black, Khaki, Olive, Grey', 999, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 42),
  ('Straight Fit Jeans - Classic', 'Classic straight fit jeans for everyday wear. Sizes: 28, 30, 32, 34, 36, 38. Colors: Blue, Black, Grey', 1099, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 45),
  ('Cotton Trousers - Casual', 'Comfortable cotton trousers for casual occasions. Available in 30, 32, 34, 36. Colors: Beige, Khaki, Grey, Navy', 899, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 40),
  ('Linen Pants - Summer', 'Lightweight linen pants for summer. Sizes: 30, 32, 34, 36. Colors: White, Beige, Khaki, Light Blue', 1299, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 35),
  ('Jogger Pants - Active', 'Comfortable jogger pants for active lifestyle. Available in S, M, L, XL. Colors: Black, Grey, Navy, Olive', 799, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Pants', 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800', 50),
  
  -- Belts (3 products)
  ('Leather Formal Belt - Premium', 'Premium leather belt for formal wear. Sizes: 32, 34, 36, 38, 40 inches. Colors: Black, Brown, Tan', 699, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Belts', 'https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=800', 40),
  ('Casual Canvas Belt - Stylish', 'Stylish canvas belt for casual outfits. Available in 30, 32, 34, 36, 38 inches. Colors: Black, Brown, Navy, Grey', 399, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Belts', 'https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=800', 50),
  ('Reversible Belt - Versatile', 'Versatile reversible belt with two colors. Sizes: 32, 34, 36, 38 inches. Color combinations: Black-Brown, Brown-Tan', 599, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Belts', 'https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=800', 35),
  
  -- Watches (2 products)
  ('Analog Watch - Classic', 'Classic analog watch with leather strap. Available in multiple dial colors: Black, Silver, Gold, Blue', 1999, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Watches', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', 25),
  ('Digital Sports Watch - Feature Rich', 'Feature-rich digital sports watch with multiple functions. Colors: Black, Blue, Red, Green', 2499, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Watches', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', 20),
  
  -- Footwear (2 products)
  ('Formal Leather Shoes - Premium', 'Premium leather formal shoes. Sizes: 7, 8, 9, 10, 11. Colors: Black, Brown, Tan', 2999, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Footwear', 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800', 20),
  ('Casual Sneakers - Comfort', 'Comfortable casual sneakers for daily wear. Available in sizes 7-11. Colors: White, Black, Navy, Grey', 1999, (SELECT id FROM categories WHERE slug = 'mens-fashion'), 'Footwear', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', 30);

-- ============================================
-- 3. KIDS & TOYS (35 products)
-- ============================================
INSERT INTO public.products (name, description, price, category_id, subcategory, image_url, stock) VALUES
  -- Kids Clothing (12 products)
  ('Boys Cotton T-Shirt Set - Pack of 3', 'Comfortable cotton t-shirt set for boys. Available in sizes: 3-4Y, 5-6Y, 7-8Y, 9-10Y, 11-12Y. Colors: Blue, Red, Green, Yellow', 599, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800', 50),
  ('Girls Frock Dress - Floral', 'Beautiful floral frock dress for girls. Sizes: 2-3Y, 4-5Y, 6-7Y, 8-9Y, 10-11Y. Colors: Pink, Blue, Yellow, Purple', 899, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800', 40),
  ('Kids Denim Jeans - Durable', 'Durable denim jeans for kids. Available in sizes 3-12 years. Colors: Blue, Black, Grey', 799, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800', 45),
  ('Kids Track Suit - Sports', 'Comfortable track suit for active kids. Sizes: 4-5Y, 6-7Y, 8-9Y, 10-11Y. Colors: Blue, Red, Black, Grey', 1299, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800', 35),
  ('Kids Kurta Set - Traditional', 'Traditional kurta set for kids. Available in sizes 3-10 years. Colors: White, Cream, Beige, Light Blue', 699, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800', 42),
  ('Girls Lehenga Choli - Party', 'Beautiful lehenga choli set for girls. Sizes: 3-4Y, 5-6Y, 7-8Y, 9-10Y. Colors: Pink, Red, Blue, Purple', 1999, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800', 30),
  ('Kids Winter Jacket - Warm', 'Warm winter jacket for kids. Available in sizes 4-12 years. Colors: Red, Blue, Black, Navy', 1499, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800', 38),
  ('Kids School Uniform Set', 'Complete school uniform set. Sizes: 4-5Y, 6-7Y, 8-9Y, 10-11Y. Colors: White shirt with Navy/Grey pants/skirt', 999, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800', 50),
  ('Kids Casual Shorts - Summer', 'Comfortable casual shorts for summer. Available in sizes 3-10 years. Colors: Khaki, Navy, Grey, Beige', 499, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800', 55),
  ('Girls Party Dress - Fancy', 'Fancy party dress for girls. Sizes: 3-4Y, 5-6Y, 7-8Y, 9-10Y. Colors: Pink, Purple, Blue, Red', 1599, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800', 28),
  ('Kids Pajama Set - Comfort', 'Comfortable pajama set for kids. Available in sizes 3-12 years. Colors: Blue, Pink, Green, Yellow', 599, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800', 48),
  ('Kids Raincoat - Waterproof', 'Waterproof raincoat for kids. Sizes: 4-5Y, 6-7Y, 8-9Y, 10-11Y. Colors: Yellow, Blue, Red, Green', 799, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Kids Clothing', 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800', 40),
  
  -- Toys (12 products)
  ('Building Blocks Set - Educational', 'Educational building blocks set with 100+ pieces. Suitable for ages 3-8 years. Colors: Multi-color', 899, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 35),
  ('Remote Control Car - Electric', 'Electric remote control car with LED lights. Suitable for ages 6+. Colors: Red, Blue, Yellow, Black', 1299, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 30),
  ('Doll House - Complete Set', 'Complete doll house with furniture and accessories. Suitable for ages 4-10 years', 2499, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 20),
  ('Action Figure Set - Superhero', 'Superhero action figure set with accessories. Suitable for ages 5+. Multiple character options', 599, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 45),
  ('Puzzle Set - 500 Pieces', 'Educational puzzle set with 500 pieces. Suitable for ages 8+. Multiple design options', 699, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 40),
  ('Musical Toy Piano - Keyboard', 'Musical keyboard piano for kids. Suitable for ages 3+. Colors: Pink, Blue, White', 1499, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 25),
  ('Soft Toy Bear - Plush', 'Soft plush teddy bear. Available in multiple sizes: Small, Medium, Large. Colors: Brown, Pink, Blue, White', 499, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 50),
  ('LEGO Style Building Set', 'Compatible building blocks set with 200+ pieces. Suitable for ages 5-12 years. Multiple color options', 1799, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 32),
  ('Board Game - Snakes & Ladders', 'Classic Snakes and Ladders board game. Suitable for ages 4+. 2-4 players', 399, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 55),
  ('Toy Kitchen Set - Pretend Play', 'Complete toy kitchen set for pretend play. Suitable for ages 3-8 years. Multiple accessories included', 1999, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 28),
  ('RC Helicopter - Mini', 'Mini remote control helicopter with LED lights. Suitable for ages 8+. Colors: Red, Blue, Black', 1599, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 22),
  ('Art & Craft Set - Complete', 'Complete art and craft set with colors, brushes, and papers. Suitable for ages 5+. Multiple color options', 799, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Toys', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 38),
  
  -- School Supplies (6 products)
  ('School Bag - Backpack Style', 'Durable school backpack with multiple compartments. Available in sizes: Small, Medium, Large. Colors: Blue, Red, Black, Pink, Grey', 899, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'School Supplies', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 40),
  ('Lunch Box Set - Bento Style', 'Bento style lunch box set with water bottle. Colors: Blue, Pink, Green, Yellow, Red', 599, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'School Supplies', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 45),
  ('Geometry Box - Complete', 'Complete geometry box with compass, protractor, and ruler. Suitable for ages 8+. Colors: Blue, Red, Black', 299, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'School Supplies', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 60),
  ('Pencil Case - Zipper', 'Zipper pencil case with multiple compartments. Colors: Blue, Pink, Black, Red, Green', 199, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'School Supplies', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 70),
  ('Water Bottle - Stainless Steel', 'Stainless steel water bottle with leak-proof cap. Available in 500ml and 750ml. Colors: Blue, Pink, Green, Black', 499, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'School Supplies', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 50),
  ('Notebook Set - Pack of 5', 'Set of 5 ruled notebooks (200 pages each). Suitable for all ages. Multiple cover colors', 399, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'School Supplies', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 55),
  
  -- Games (5 products)
  ('Chess Set - Wooden', 'Classic wooden chess set with board. Suitable for ages 8+. Complete with all pieces', 799, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Games', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 35),
  ('Carrom Board - Professional', 'Professional carrom board with striker and coins. Suitable for ages 6+. 2-4 players', 1499, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Games', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 25),
  ('Ludo Game Set - Classic', 'Classic Ludo game set with dice and tokens. Suitable for ages 4+. 2-4 players', 499, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Games', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 40),
  ('Card Game Set - Multiple Games', 'Card game set with multiple games (Uno, Rummy, etc.). Suitable for ages 6+. Multiple game options', 599, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Games', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 38),
  ('Jigsaw Puzzle - 1000 Pieces', 'Challenging 1000-piece jigsaw puzzle. Suitable for ages 10+. Multiple design options', 899, (SELECT id FROM categories WHERE slug = 'kids-toys'), 'Games', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800', 30);

-- ============================================
-- 4. HOME & KITCHEN (35 products)
-- ============================================
INSERT INTO public.products (name, description, price, category_id, subcategory, image_url, stock) VALUES
  -- Kitchenware (12 products)
  ('Non-Stick Cookware Set - 5 Pieces', 'Premium non-stick cookware set with 5 pieces. Includes fry pan, kadai, tawa, and lids. Colors: Black, Red, Blue', 2499, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 30),
  ('Stainless Steel Pressure Cooker - 5L', 'Durable stainless steel pressure cooker 5L capacity. Suitable for 4-6 people. Silver finish', 1299, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 35),
  ('Ceramic Dinner Set - 24 Pieces', 'Beautiful ceramic dinner set with 24 pieces. Includes plates, bowls, and mugs. Colors: White, Blue, Green', 1999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 28),
  ('Glass Storage Containers Set - 10 Pieces', 'Airtight glass storage containers set. Available in multiple sizes. Perfect for food storage', 899, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 40),
  ('Knife Set - 6 Pieces', 'Premium stainless steel knife set with wooden block. Includes chef knife, bread knife, and utility knives', 1499, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 32),
  ('Cutting Board Set - Bamboo', 'Eco-friendly bamboo cutting board set. Includes 3 different sizes. Natural finish', 599, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 45),
  ('Silicone Spatula Set - 5 Pieces', 'Heat-resistant silicone spatula set. Includes various sizes and shapes. Colors: Red, Blue, Green, Black', 399, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 50),
  ('Steel Tiffin Box - 3 Tier', 'Stainless steel 3-tier tiffin box. Leak-proof design. Perfect for lunch. Silver finish', 699, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 42),
  ('Coffee Maker - Electric', 'Electric coffee maker with auto shut-off. Capacity: 1.25L. Colors: Black, White, Red', 2499, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 25),
  ('Mixer Grinder - 750W', 'Powerful 750W mixer grinder with 3 jars. Stainless steel blades. Colors: White, Red, Blue', 2999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 22),
  ('Kitchen Scale - Digital', 'Digital kitchen scale with LCD display. Capacity: 5kg. Precision: 1g. Colors: White, Black', 799, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 38),
  ('Steel Utensil Set - 12 Pieces', 'Complete stainless steel utensil set. Includes spoons, ladles, and serving spoons. Silver finish', 1299, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Kitchenware', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 35),
  
  -- Home Decor (8 products)
  ('Wall Clock - Modern Design', 'Modern wall clock with silent movement. Available in 12" and 15" sizes. Colors: Black, White, Brown, Silver', 899, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Home Decor', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 40),
  ('Table Lamp - LED', 'Energy-efficient LED table lamp with adjustable brightness. Colors: White, Black, Gold, Silver', 699, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Home Decor', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 35),
  ('Photo Frame Set - 6 Pieces', 'Set of 6 photo frames in different sizes. Wooden and metal options. Colors: Brown, Black, White, Gold', 599, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Home Decor', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 45),
  ('Curtain Set - Ready Made', 'Ready-made curtain set with matching valance. Available in multiple sizes. Colors: Beige, Blue, Grey, Brown', 1299, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Home Decor', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 30),
  ('Wall Art - Canvas Print', 'Beautiful canvas wall art print. Multiple designs available. Sizes: 12x16, 16x20, 20x24 inches', 799, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Home Decor', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 38),
  ('Vase Set - Ceramic', 'Elegant ceramic vase set. Includes 3 different sizes. Colors: White, Blue, Green, Terracotta', 499, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Home Decor', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 42),
  ('Cushion Cover Set - 4 Pieces', 'Decorative cushion cover set with 4 pieces. Multiple designs and colors available', 399, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Home Decor', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 50),
  ('Rug - Area Carpet', 'Soft area rug for living room. Available in multiple sizes. Colors: Beige, Grey, Blue, Brown', 1999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Home Decor', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 28),
  
  -- Furniture (5 products)
  ('Study Table - Wooden', 'Durable wooden study table with drawer. Suitable for home office. Colors: Brown, White, Black', 3999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Furniture', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 20),
  ('Dining Chair Set - 4 Pieces', 'Comfortable dining chair set with 4 chairs. Upholstered seats. Colors: Brown, Black, Beige', 4999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Furniture', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 18),
  ('Bookshelf - 5 Tier', 'Spacious 5-tier bookshelf. Wooden construction. Colors: Brown, White, Black', 2999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Furniture', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 22),
  ('Coffee Table - Glass Top', 'Modern coffee table with glass top. Wooden base. Colors: Brown, Black, White', 3499, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Furniture', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 25),
  ('Shoe Rack - Metal', 'Sturdy metal shoe rack with 4 tiers. Space-saving design. Colors: Black, White, Silver', 1499, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Furniture', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 30),
  
  -- Appliances (5 products)
  ('Electric Kettle - 1.5L', 'Stainless steel electric kettle with auto shut-off. Capacity: 1.5L. Colors: White, Black, Silver', 999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Appliances', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 35),
  ('Toaster - 2 Slice', '2-slice toaster with multiple browning settings. Colors: White, Black, Red, Silver', 1299, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Appliances', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 32),
  ('Iron - Steam', 'Steam iron with non-stick soleplate. Power: 1200W. Colors: White, Blue, Pink, Black', 899, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Appliances', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 40),
  ('Table Fan - 16 Inch', '16-inch table fan with 3-speed settings. Oscillating feature. Colors: White, Black, Grey', 1499, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Appliances', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 28),
  ('Air Purifier - HEPA Filter', 'HEPA air purifier for rooms up to 300 sq ft. Multiple filter stages. Colors: White, Black', 4999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Appliances', 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=800', 15),
  
  -- Bedding (5 products)
  ('Bed Sheet Set - Cotton', 'Premium cotton bed sheet set. Includes bed sheet, pillow covers. Sizes: Single, Double, King. Colors: White, Blue, Pink, Beige', 1299, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Bedding', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 35),
  ('Comforter Set - All Season', 'All-season comforter set with matching pillow covers. Sizes: Single, Double, King. Colors: Blue, Grey, Beige, White', 2499, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Bedding', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 28),
  ('Pillow Set - Memory Foam', 'Memory foam pillow set of 2. Orthopedic support. Sizes: Standard, Queen, King', 899, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Bedding', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 40),
  ('Mattress Protector - Waterproof', 'Waterproof mattress protector. Fitted sheet style. Sizes: Single, Double, King. Colors: White, Beige', 699, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Bedding', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 45),
  ('Blanket - Fleece', 'Soft fleece blanket. Available in multiple sizes. Colors: Blue, Grey, Beige, Pink, White', 999, (SELECT id FROM categories WHERE slug = 'home-kitchen'), 'Bedding', 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800', 38);

-- Note: Due to file size, remaining categories (Beauty, Bags, Watches, Sports, Stationery) will be added in a continuation
-- This file already contains 140+ products across 4 categories

