-- Migration: Enhanced Detailed Product Data Part 3
-- Continuation of detailed products for remaining categories
-- All products include Indian brands, specific styles, size variations, and realistic pricing
-- All prices are in Indian Rupees (INR)

-- ============================================
-- 5. BEAUTY & PERSONAL CARE (35+ products)
-- Brands: Lakme, Maybelline, Himalaya, Biotique | Types: Skincare, Makeup, Haircare
-- Price Range: ₹199 - ₹2999 | Sizes: Various (ml, g, pieces)
-- ============================================
INSERT INTO public.products (name, description, price, category_id, subcategory, image_url, stock) VALUES
  -- Skincare (10 products)
  ('Lakme Face Wash - Vitamin C', 'Lakme brightening face wash with Vitamin C. Removes tan and brightens skin. Suitable for all skin types. Size: 100ml, 200ml. For daily use', 299, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Skincare', 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800', 50),
  ('Himalaya Moisturizing Cream - SPF 30', 'Himalaya daily moisturizing cream with SPF 30 protection. Natural ingredients. Size: 50g, 100g. Suitable for all skin types', 499, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Skincare', 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800', 45),
  ('Biotique Face Serum - Anti-Aging', 'Biotique anti-aging face serum with retinol. Reduces fine lines. Size: 30ml. For mature skin. Use at night', 899, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Skincare', 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800', 35),
  ('Lakme Face Mask - Clay', 'Lakme deep cleansing clay face mask. Removes impurities. Size: 100g. Suitable for oily skin. Use 2-3 times a week', 399, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Skincare', 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800', 40),
  ('Himalaya Sunscreen Lotion - SPF 50', 'Himalaya high protection sunscreen lotion SPF 50. Prevents tanning. Size: 100ml, 200ml. Water-resistant. For all skin types', 599, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Skincare', 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800', 48),
  ('Biotique Face Toner - Rose Water', 'Biotique hydrating face toner with rose water. Natural ingredients. Size: 200ml. Suitable for all skin types. Alcohol-free', 349, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Skincare', 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800', 42),
  ('Lakme Night Cream - Nourishing', 'Lakme nourishing night cream with hyaluronic acid. Deep hydration. Size: 50g. For dry and normal skin', 699, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Skincare', 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800', 38),
  ('Himalaya Face Scrub - Exfoliating', 'Himalaya gentle exfoliating face scrub. Removes dead skin. Size: 75g. Suitable for all skin types. Use 2-3 times a week', 449, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Skincare', 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800', 44),
  ('Biotique Under Eye Cream - Anti-Dark Circles', 'Biotique anti-dark circles under eye cream. Reduces puffiness. Size: 15g. For all skin types. Use morning and night', 799, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Skincare', 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800', 36),
  ('Lakme Face Cleansing Oil - Deep Clean', 'Lakme deep cleansing face oil. Removes makeup effectively. Size: 150ml. Suitable for all skin types. Natural oils', 549, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Skincare', 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=800', 40),
  
  -- Makeup (10 products)
  ('Lakme Lipstick Set - 5 Shades', 'Lakme long-lasting lipstick set with 5 shades. Matte finish. Colors: Red, Pink, Nude, Coral, Berry. Size: 4.5g each', 999, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Makeup', 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800', 35),
  ('Maybelline Foundation - Full Coverage', 'Maybelline full coverage foundation. Flawless finish. Available in multiple shades. Size: 30ml. Suitable for all skin types', 1299, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Makeup', 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800', 30),
  ('Lakme Kajal Pencil - Waterproof', 'Lakme waterproof kajal pencil. Long-lasting. Colors: Black, Brown. Size: 0.35g. Smudge-proof', 199, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Makeup', 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800', 60),
  ('Maybelline Mascara - Volumizing', 'Maybelline volumizing mascara. Dramatic lashes. Colors: Black, Brown. Waterproof. Size: 8ml', 499, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Makeup', 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800', 45),
  ('Lakme Compact Powder - Matte', 'Lakme matte finish compact powder. Oil-control. Available in multiple shades. Size: 9g. Long-lasting', 599, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Makeup', 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800', 40),
  ('Maybelline Blush - Powder', 'Maybelline powder blush. Natural finish. Colors: Pink, Peach, Rose. Size: 5g. Buildable color', 399, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Makeup', 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800', 42),
  ('Lakme Eye Shadow Palette - 12 Shades', 'Lakme 12-shade eye shadow palette. Multiple color combinations. Long-lasting. Size: 12g. Professional quality', 899, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Makeup', 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800', 38),
  ('Maybelline Concealer - High Coverage', 'Maybelline high coverage concealer. Hides imperfections. Available in multiple shades. Size: 6ml. For dark circles and blemishes', 699, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Makeup', 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800', 35),
  ('Lakme Lip Gloss Set - 3 Shades', 'Lakme shiny lip gloss set with 3 shades. Non-sticky formula. Colors: Clear, Pink, Nude. Size: 4ml each', 499, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Makeup', 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800', 44),
  ('Maybelline Makeup Brush Set - 12 Pieces', 'Maybelline professional makeup brush set with 12 pieces. Synthetic bristles. Multiple brush types. Perfect for complete makeup', 1299, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Makeup', 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800', 28),
  
  -- Haircare (8 products)
  ('Himalaya Shampoo - Anti-Dandruff', 'Himalaya anti-dandruff shampoo. Natural ingredients. Size: 200ml, 400ml. For all hair types. Contains tea tree oil', 299, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Haircare', 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800', 50),
  ('Biotique Conditioner - Nourishing', 'Biotique nourishing hair conditioner. Natural herbs. Size: 200ml, 400ml. For dry and damaged hair', 349, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Haircare', 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800', 48),
  ('Himalaya Hair Oil - Coconut', 'Himalaya pure coconut hair oil. Promotes hair growth. Size: 200ml, 500ml. For hair growth and nourishment', 399, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Haircare', 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800', 45),
  ('Biotique Hair Serum - Frizz Control', 'Biotique frizz control hair serum. Smooth hair. Size: 100ml. For all hair types. Heat protection', 599, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Haircare', 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800', 40),
  ('Himalaya Hair Mask - Deep Conditioning', 'Himalaya deep conditioning hair mask. Repairs damage. Size: 200g. For damaged hair. Use once a week', 699, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Haircare', 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800', 38),
  ('Biotique Hair Spray - Strong Hold', 'Biotique strong hold hair spray. Long-lasting hold. Size: 200ml. For all hair types. Natural ingredients', 449, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Haircare', 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800', 42),
  ('Himalaya Hair Color - Natural', 'Himalaya natural hair color. Ammonia-free. Available in multiple shades. Size: 100ml. Gentle on hair', 799, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Haircare', 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800', 35),
  ('Biotique Hair Brush Set - Detangling', 'Biotique detangling hair brush set. Includes 3 different brush types. Suitable for all hair types. Natural bristles', 499, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Haircare', 'https://images.unsplash.com/photo-1571875257727-256c39da42af?w=800', 44),
  
  -- Fragrances (4 products)
  ('Fogg Perfume - Floral', 'Fogg long-lasting floral perfume. Elegant fragrance. Size: 50ml, 100ml. For women. Fragrance lasts 8-10 hours', 1299, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Fragrances', 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800', 30),
  ('Wild Stone Cologne - Fresh', 'Wild Stone fresh cologne for men. Masculine fragrance. Size: 100ml. Long-lasting. Suitable for daily use', 999, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Fragrances', 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800', 35),
  ('Fogg Body Mist - Light', 'Fogg light body mist. Refreshing fragrance. Size: 200ml. Multiple fragrances available. Perfect for daily use', 499, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Fragrances', 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800', 45),
  ('Wild Stone Perfume Set - Mini', 'Wild Stone mini perfume set with 5 different fragrances. Perfect for travel. Size: 5ml each. Multiple scents', 799, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Fragrances', 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800', 40),
  
  -- Personal Care (3 products)
  ('Colgate Toothbrush Set - Electric', 'Colgate electric toothbrush set with 2 brush heads. Multiple cleaning modes. Rechargeable. Perfect oral care', 1499, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Personal Care', 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=800', 32),
  ('Vaseline Body Lotion - Moisturizing', 'Vaseline moisturizing body lotion. Deep hydration. Size: 400ml. For all skin types. Contains shea butter', 499, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Personal Care', 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=800', 48),
  ('Nivea Deodorant - Roll On', 'Nivea long-lasting roll-on deodorant. Fresh fragrance. Size: 50ml. Multiple fragrances. 48-hour protection', 299, (SELECT id FROM categories WHERE slug = 'beauty-personal-care'), 'Personal Care', 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=800', 55);

-- ============================================
-- 6. BAGS & FOOTWEAR (35+ products)
-- Brands: Skybags, American Tourister, Bata, Red Tape | Types: Handbags, Backpacks, Shoes
-- Price Range: ₹499 - ₹4999 | Sizes: Various (Small, Medium, Large for bags, 6-11 for shoes)
-- ============================================
INSERT INTO public.products (name, description, price, category_id, subcategory, image_url, stock) VALUES
  -- Handbags (10 products)
  ('Hidesign Leather Handbag - Tote', 'Hidesign premium leather tote handbag. Spacious and elegant. Size: Large. Colors: Black, Brown, Tan, Red. Multiple compartments. Material: Genuine Leather', 2999, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Handbags', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800', 25),
  ('Baggit Designer Handbag - Shoulder', 'Baggit designer shoulder handbag. Trendy design. Size: Medium. Colors: Black, Navy, Beige, Pink. Gold hardware. Material: Premium Synthetic Leather', 1999, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Handbags', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800', 30),
  ('Caprese Crossbody Bag - Small', 'Caprese small crossbody bag. Perfect for essentials. Size: Small. Colors: Black, Brown, Red, Blue. Adjustable strap. Material: Premium Faux Leather', 1499, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Handbags', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800', 35),
  ('Hidesign Clutch Bag - Evening', 'Hidesign elegant evening clutch bag. Perfect for parties. Size: Small. Colors: Black, Gold, Silver, Red. Material: Premium Leather', 999, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Handbags', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800', 40),
  ('Baggit Satchel Bag - Classic', 'Baggit classic satchel bag. Timeless design. Size: Medium. Colors: Brown, Black, Tan, Navy. Multiple pockets. Material: Durable Synthetic Leather', 1799, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Handbags', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800', 32),
  ('Caprese Hobo Bag - Casual', 'Caprese casual hobo bag. Comfortable design. Size: Large. Colors: Beige, Grey, Black, Brown. Comfortable shoulder strap. Material: Soft Faux Leather', 1299, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Handbags', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800', 38),
  ('Hidesign Bucket Bag - Trendy', 'Hidesign trendy bucket bag. Modern design. Size: Medium. Colors: Black, Brown, Tan, Red. Drawstring closure. Material: Premium Leather', 2199, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Handbags', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800', 28),
  ('Baggit Messenger Bag - Unisex', 'Baggit unisex messenger bag. Functional design. Size: Large. Colors: Black, Brown, Navy, Grey. Multiple compartments. Material: Durable Canvas', 999, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Handbags', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800', 42),
  ('Caprese Wristlet Bag - Small', 'Caprese small wristlet bag. Perfect for essentials. Size: Small. Colors: Black, Brown, Pink, Blue. Material: Premium Faux Leather', 699, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Handbags', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800', 45),
  ('Hidesign Sling Bag - Compact', 'Hidesign compact sling bag. Modern design. Size: Small. Colors: Black, Navy, Red, Grey. Adjustable strap. Material: Premium Leather', 899, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Handbags', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800', 40),
  
  -- Backpacks (8 products)
  ('Skybags Laptop Backpack - 15.6 Inch', 'Skybags durable laptop backpack for 15.6 inch laptops. Padded compartment. Colors: Black, Navy, Grey, Red. Multiple pockets. Material: Durable Polyester', 1999, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Backpacks', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 35),
  ('American Tourister School Backpack - Kids', 'American Tourister colorful kids school backpack. Fun designs. Size: Medium. Colors: Blue, Pink, Red, Black. Multiple compartments. Material: Durable Polyester', 899, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Backpacks', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 40),
  ('Skybags Travel Backpack - 40L', 'Skybags large travel backpack 40L capacity. Perfect for travel. Colors: Black, Navy, Grey. Water-resistant. Multiple pockets. Material: Durable Nylon', 2499, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Backpacks', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 30),
  ('American Tourister Sports Backpack - Gym', 'American Tourister gym sports backpack. Functional design. Size: Medium. Colors: Black, Red, Blue, Grey. Shoe compartment. Material: Durable Polyester', 1499, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Backpacks', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 32),
  ('Skybags Mini Backpack - Fashion', 'Skybags fashion mini backpack. Trendy design. Size: Small. Colors: Black, Pink, Blue, Brown. Material: Durable Polyester', 1299, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Backpacks', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 38),
  ('American Tourister Hiking Backpack - 30L', 'American Tourister durable hiking backpack 30L. Outdoor adventure. Colors: Green, Black, Grey. Water-resistant. Multiple compartments. Material: Durable Nylon', 2999, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Backpacks', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 25),
  ('Skybags College Backpack - Casual', 'Skybags casual college backpack. Spacious design. Size: Large. Colors: Black, Navy, Grey, Red. Laptop compartment. Material: Durable Polyester', 1799, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Backpacks', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 35),
  ('American Tourister Daypack - Lightweight', 'American Tourister lightweight daypack. Perfect for day trips. Size: Small. Colors: Black, Blue, Grey, Green. Material: Lightweight Nylon', 999, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Backpacks', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', 42),
  
  -- Wallets (5 products)
  ('Hidesign Leather Wallet - Men', 'Hidesign premium leather wallet for men. Multiple card slots. Colors: Black, Brown, Tan. RFID blocking. Material: Genuine Leather', 799, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Wallets', 'https://images.unsplash.com/photo-1627123424574-724758594ecc?w=800', 45),
  ('Caprese Ladies Wallet - Long', 'Caprese long ladies wallet with coin compartment. Functional design. Colors: Black, Brown, Pink, Red. Multiple card slots. Material: Premium Faux Leather', 699, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Wallets', 'https://images.unsplash.com/photo-1627123424574-724758594ecc?w=800', 40),
  ('Baggit Card Holder - Slim', 'Baggit slim card holder. Minimalist design. Colors: Black, Brown, Blue, Red. Holds 6-8 cards. Material: Premium Synthetic Leather', 399, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Wallets', 'https://images.unsplash.com/photo-1627123424574-724758594ecc?w=800', 50),
  ('Hidesign Bifold Wallet - Classic', 'Hidesign classic bifold wallet. Timeless design. Colors: Black, Brown, Tan. Multiple compartments. Material: Genuine Leather', 599, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Wallets', 'https://images.unsplash.com/photo-1627123424574-724758594ecc?w=800', 48),
  ('Caprese Travel Wallet - Passport', 'Caprese travel wallet with passport holder. Perfect for travel. Colors: Black, Brown, Navy. Multiple pockets. Material: Durable Synthetic Leather', 999, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Wallets', 'https://images.unsplash.com/photo-1627123424574-724758594ecc?w=800', 35),
  
  -- Shoes (7 products)
  ('Bata Running Shoes - Sports', 'Bata comfortable running shoes for sports. Cushioned sole. Sizes: 6-11. Colors: White, Black, Blue, Red. Material: Synthetic Upper, Rubber Sole', 2499, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Shoes', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', 30),
  ('Red Tape Casual Sneakers - Everyday', 'Red Tape everyday casual sneakers. Comfortable fit. Sizes: 6-11. Colors: White, Black, Grey, Navy. Material: Synthetic Upper, Rubber Sole', 1999, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Shoes', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', 35),
  ('Bata Formal Leather Shoes - Premium', 'Bata premium leather formal shoes. Classic design. Sizes: 7-11. Colors: Black, Brown, Tan. Material: Genuine Leather', 2999, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Shoes', 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800', 28),
  ('Red Tape Canvas Shoes - Casual', 'Red Tape comfortable canvas casual shoes. Lightweight. Sizes: 6-11. Colors: White, Black, Blue, Red. Material: Canvas Upper, Rubber Sole', 1299, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Shoes', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', 40),
  ('Bata Boots - Ankle', 'Bata stylish ankle boots. Perfect for winter. Sizes: 6-10. Colors: Black, Brown, Tan. Material: Genuine Leather', 3499, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Shoes', 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800', 25),
  ('Red Tape Loafers - Comfort', 'Red Tape comfortable loafers. Slip-on design. Sizes: 7-11. Colors: Black, Brown, Tan, Navy. Material: Genuine Leather', 2199, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Shoes', 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800', 32),
  ('Bata High-Top Sneakers - Street', 'Bata street style high-top sneakers. Trendy design. Sizes: 6-11. Colors: Black, White, Red, Blue. Material: Synthetic Upper, Rubber Sole', 2799, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Shoes', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', 30),
  
  -- Sandals (5 products)
  ('Bata Flip Flops - Beach', 'Bata comfortable beach flip flops. Water-resistant. Sizes: 6-11. Colors: Black, Blue, Red, Green. Material: EVA Sole', 499, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Sandals', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', 50),
  ('Red Tape Strap Sandals - Casual', 'Red Tape casual strap sandals. Adjustable straps. Sizes: 6-10. Colors: Black, Brown, Tan, Beige. Material: Synthetic Upper, Rubber Sole', 899, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Sandals', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', 42),
  ('Bata Sport Sandals - Hiking', 'Bata durable hiking sport sandals. Quick-dry. Sizes: 7-11. Colors: Black, Grey, Blue. Material: Durable Synthetic', 1499, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Sandals', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', 35),
  ('Red Tape Wedge Sandals - Fashion', 'Red Tape fashion wedge sandals. Comfortable heel. Sizes: 6-9. Colors: Black, Brown, Tan, Beige. Material: Synthetic Upper, Rubber Sole', 1299, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Sandals', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', 38),
  ('Bata Gladiator Sandals - Trendy', 'Bata trendy gladiator sandals. Multiple straps. Sizes: 6-10. Colors: Black, Brown, Tan. Material: Synthetic Upper, Rubber Sole', 1099, (SELECT id FROM categories WHERE slug = 'bags-footwear'), 'Sandals', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', 40);

-- ============================================
-- 7. WATCHES & ACCESSORIES (35+ products)
-- Brands: Titan, Fastrack, Sonata | Types: Watches, Jewelry, Sunglasses
-- Price Range: ₹499 - ₹4999 | Sizes: Various (Watch sizes, Jewelry sizes)
-- ============================================
INSERT INTO public.products (name, description, price, category_id, subcategory, image_url, stock) VALUES
  -- Watches (12 products)
  ('Titan Smart Watch - Fitness', 'Titan feature-rich smartwatch with fitness tracking. Heart rate monitor. Colors: Black, Silver, Rose Gold. Water-resistant. Material: Stainless Steel Case', 4999, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Watches', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', 20),
  ('Fastrack Analog Watch - Classic', 'Fastrack classic analog watch with leather strap. Elegant timepiece. Colors: Black, Silver, Gold, Blue dial. Water-resistant. Material: Stainless Steel Case, Leather Strap', 1999, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Watches', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', 30),
  ('Titan Digital Watch - Sports', 'Titan digital sports watch with multiple functions. Stopwatch feature. Colors: Black, Blue, Red, Green. Material: Resin Case, Silicone Strap', 2499, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Watches', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', 28),
  ('Sonata Chronograph Watch - Men', 'Sonata men chronograph watch with multiple dials. Professional design. Colors: Black, Silver, Gold. Material: Stainless Steel', 3499, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Watches', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', 25),
  ('Titan Ladies Watch - Elegant', 'Titan elegant ladies watch with diamond accents. Delicate design. Colors: Silver, Gold, Rose Gold. Material: Stainless Steel with Crystal Accents', 2999, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Watches', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', 22),
  ('Fastrack Kids Watch - Colorful', 'Fastrack colorful kids watch with fun designs. Water-resistant. Colors: Blue, Pink, Red, Green. Material: Durable Plastic', 799, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Watches', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', 40),
  ('Titan Automatic Watch - Mechanical', 'Titan mechanical automatic watch. Self-winding. Colors: Black, Silver, Blue dial. Material: Stainless Steel with Automatic Movement', 4999, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Watches', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', 18),
  ('Fastrack Fitness Tracker - Band', 'Fastrack fitness tracker band with heart rate monitor. Sleep tracking. Colors: Black, Blue, Pink, Green. Material: Silicone Band', 1999, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Watches', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', 35),
  ('Titan Diving Watch - Waterproof', 'Titan waterproof diving watch. Professional grade. Colors: Black, Blue, Orange. 200m water resistance. Material: Stainless Steel', 4499, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Watches', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', 20),
  ('Sonata Pilot Watch - Aviator', 'Sonata aviator pilot watch with large dial. Easy to read. Colors: Black, Silver, Brown. Material: Stainless Steel', 3999, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Watches', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', 23),
  ('Fastrack Minimalist Watch - Simple', 'Fastrack simple minimalist watch. Clean design. Colors: White, Black, Brown dial. Material: Stainless Steel Case', 1499, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Watches', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', 38),
  ('Titan Luxury Watch - Gold', 'Titan luxury gold watch with premium finish. Elegant timepiece. Colors: Gold, Rose Gold. Material: Premium Stainless Steel with Gold Plating', 4999, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Watches', 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800', 15),
  
  -- Jewelry (10 products)
  ('Tanishq Gold Earrings - Stud', 'Tanishq gold plated stud earrings. Elegant design. Colors: Gold, Rose Gold, Silver. Hypoallergenic. Material: Gold Plated', 999, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Jewelry', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800', 40),
  ('PC Jeweller Silver Necklace - Chain', 'PC Jeweller elegant silver chain necklace. Traditional design. Length: 18-20 inches. Adjustable. Multiple designs. Material: Sterling Silver', 1299, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Jewelry', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800', 35),
  ('Tanishq Bracelet Set - 3 Pieces', 'Tanishq bracelet set with 3 pieces. Mix and match. Colors: Gold, Silver, Rose Gold. Material: Gold Plated', 799, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Jewelry', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800', 42),
  ('PC Jeweller Ring Set - Stackable', 'PC Jeweller stackable ring set with 5 rings. Multiple sizes. Colors: Gold, Silver, Rose Gold. Material: Gold Plated', 599, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Jewelry', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800', 45),
  ('Tanishq Anklet - Delicate', 'Tanishq delicate anklet with charms. Traditional design. Colors: Silver, Gold. Adjustable length. Material: Gold Plated', 399, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Jewelry', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800', 48),
  ('PC Jeweller Pendant Set - Gold', 'PC Jeweller gold pendant set with chain. Multiple pendant designs. Colors: Gold, Rose Gold. Material: Gold Plated', 1499, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Jewelry', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800', 32),
  ('Tanishq Nose Pin - Traditional', 'Tanishq traditional nose pin. Multiple designs. Colors: Gold, Silver. Hypoallergenic. Material: Gold Plated', 299, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Jewelry', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800', 50),
  ('PC Jeweller Bangle Set - 6 Pieces', 'PC Jeweller bangle set with 6 pieces. Traditional design. Colors: Gold, Silver, Rose Gold. Material: Gold Plated', 899, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Jewelry', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800', 38),
  ('Tanishq Choker - Fashion', 'Tanishq fashion choker necklace. Trendy design. Colors: Black, Gold, Silver. Adjustable. Material: Gold Plated with Synthetic Stones', 499, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Jewelry', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800', 44),
  ('PC Jeweller Toe Ring Set - 5 Pieces', 'PC Jeweller toe ring set with 5 pieces. Traditional design. Colors: Silver, Gold. Multiple sizes. Material: Gold Plated', 399, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Jewelry', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800', 46),
  
  -- Sunglasses (8 products)
  ('Titan Aviator Sunglasses - Classic', 'Titan classic aviator sunglasses. UV protection. Colors: Black, Brown, Gold frame. Material: UV400 Protection Lenses', 999, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Sunglasses', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800', 40),
  ('Fastrack Wayfarer Sunglasses - Retro', 'Fastrack retro wayfarer sunglasses. Polarized lenses. Colors: Black, Brown, Tortoise frame. Material: Polarized UV400 Lenses', 1299, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Sunglasses', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800', 35),
  ('Titan Sports Sunglasses - Wraparound', 'Titan wraparound sports sunglasses. UV400 protection. Colors: Black, Blue, Red frame. Material: UV400 Protection Lenses', 1499, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Sunglasses', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800', 32),
  ('Fastrack Cat Eye Sunglasses - Vintage', 'Fastrack vintage cat eye sunglasses. Stylish design. Colors: Black, Gold, Silver frame. Material: UV400 Protection Lenses', 899, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Sunglasses', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800', 38),
  ('Titan Oversized Sunglasses - Fashion', 'Titan fashion oversized sunglasses. Large lenses. Colors: Black, Brown, Tortoise frame. Material: UV400 Protection Lenses', 1199, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Sunglasses', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800', 36),
  ('Fastrack Round Sunglasses - Hipster', 'Fastrack hipster round sunglasses. Retro style. Colors: Black, Gold, Silver frame. Material: UV400 Protection Lenses', 799, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Sunglasses', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800', 42),
  ('Titan Gradient Sunglasses - Modern', 'Titan modern gradient sunglasses. Gradient lenses. Colors: Black, Blue, Brown frame. Material: Gradient UV400 Lenses', 1099, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Sunglasses', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800', 34),
  ('Fastrack Kids Sunglasses - Fun', 'Fastrack fun kids sunglasses. UV protection. Colors: Blue, Pink, Red, Green frame. Material: UV400 Protection Lenses', 499, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Sunglasses', 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800', 45),
  
  -- Belts (5 products)
  ('Titan Leather Belt - Formal', 'Titan premium leather formal belt. Durable design. Sizes: 32, 34, 36, 38, 40 inches. Colors: Black, Brown, Tan. Material: Genuine Leather', 699, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Belts', 'https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=800', 40),
  ('Fastrack Canvas Belt - Casual', 'Fastrack stylish canvas casual belt. Modern design. Sizes: 30, 32, 34, 36, 38 inches. Colors: Black, Brown, Navy, Grey. Material: Durable Canvas', 399, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Belts', 'https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=800', 45),
  ('Titan Reversible Belt - Versatile', 'Titan versatile reversible belt with two colors. Two belts in one. Available in 32, 34, 36, 38 inches. Color combinations: Black-Brown, Brown-Tan. Material: Genuine Leather', 599, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Belts', 'https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=800', 38),
  ('Fastrack Studded Belt - Fashion', 'Fastrack fashion studded belt. Trendy design. Sizes: 30, 32, 34, 36 inches. Colors: Black, Brown. Metal studs. Material: Genuine Leather with Metal Studs', 899, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Belts', 'https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=800', 35),
  ('Titan Braided Belt - Casual', 'Titan casual braided leather belt. Classic design. Sizes: 32, 34, 36, 38 inches. Colors: Brown, Black, Tan. Material: Genuine Leather', 799, (SELECT id FROM categories WHERE slug = 'watches-accessories'), 'Belts', 'https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=800', 40);

-- ============================================
-- 8. SPORTS & FITNESS (35+ products)
-- Brands: Nike, Adidas, Reebok, Puma | Types: Sportswear, Equipment, Accessories
-- Price Range: ₹299 - ₹4999 | Sizes: S, M, L, XL, XXL (Clothing), Various (Equipment)
-- ============================================
INSERT INTO public.products (name, description, price, category_id, subcategory, image_url, stock) VALUES
  -- Sportswear (12 products)
  ('Nike Sports T-Shirt - Dry Fit', 'Nike moisture-wicking dry fit sports t-shirt. Keeps you cool. Sizes: S, M, L, XL, XXL. Colors: Black, Navy, Red, Blue. Material: Dri-FIT Fabric', 999, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sportswear', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 45),
  ('Adidas Track Pants - Comfortable', 'Adidas comfortable track pants for sports. Perfect fit. Sizes: S, M, L, XL. Colors: Black, Grey, Navy, Blue. Material: Climalite Fabric', 1499, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sportswear', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 40),
  ('Reebok Sports Shorts - Quick Dry', 'Reebok quick-dry sports shorts. Moisture management. Sizes: S, M, L, XL. Colors: Black, Navy, Grey, Red. Material: Quick-Dry Fabric', 799, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sportswear', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 42),
  ('Puma Compression Tights - Performance', 'Puma performance compression tights. Muscle support. Sizes: S, M, L, XL. Colors: Black, Navy, Grey. Material: Compression Fabric', 1999, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sportswear', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 35),
  ('Nike Sports Bra - High Support', 'Nike high support sports bra. Maximum support. Sizes: S, M, L, XL. Colors: Black, Navy, Pink, Grey. Material: Dri-FIT Fabric', 1299, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sportswear', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 38),
  ('Adidas Hoodie - Sports', 'Adidas comfortable sports hoodie. Warm and cozy. Sizes: S, M, L, XL, XXL. Colors: Black, Grey, Navy, Red. Material: Fleece Fabric', 2499, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sportswear', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 32),
  ('Reebok Tank Top - Athletic', 'Reebok athletic tank top. Breathable design. Sizes: S, M, L, XL. Colors: Black, White, Grey, Navy. Material: Quick-Dry Fabric', 699, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sportswear', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 48),
  ('Puma Leggings - Yoga', 'Puma comfortable yoga leggings. Flexible fit. Sizes: S, M, L, XL. Colors: Black, Navy, Grey, Pink. Material: Stretch Fabric', 1499, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sportswear', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 40),
  ('Nike Sports Jacket - Windproof', 'Nike windproof sports jacket. Weather protection. Sizes: S, M, L, XL. Colors: Black, Navy, Red, Blue. Material: Windproof Fabric', 2999, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sportswear', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 28),
  ('Adidas Sweatpants - Joggers', 'Adidas comfortable jogger sweatpants. Modern fit. Sizes: S, M, L, XL. Colors: Black, Grey, Navy. Material: Soft Fleece', 1799, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sportswear', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 36),
  ('Reebok Sports Socks - Pack of 3', 'Reebok moisture-wicking sports socks pack of 3. Cushioned sole. Sizes: 6-8, 9-11. Colors: White, Black, Grey. Material: Moisture-Wicking Fabric', 499, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sportswear', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 50),
  ('Puma Headband - Sweat Absorbent', 'Puma sweat absorbent headband. Keeps sweat away. Colors: Black, White, Grey, Navy. One size fits all. Material: Moisture-Wicking Fabric', 299, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sportswear', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 55),
  
  -- Equipment (10 products)
  ('Cult.fit Dumbbell Set - Adjustable', 'Cult.fit adjustable dumbbell set 2.5kg to 20kg. Multiple weight options. Perfect for home gym. Material: Cast Iron with Adjustable Weights', 3999, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Equipment', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 20),
  ('Decathlon Yoga Mat - Non-Slip', 'Decathlon non-slip yoga mat. Perfect grip. Size: 183cm x 61cm. Colors: Purple, Blue, Pink, Green. Material: TPE Material', 899, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Equipment', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 40),
  ('Cult.fit Resistance Bands Set - 5 Pieces', 'Cult.fit resistance bands set with 5 different resistance levels. Full body workout. Colors: Yellow, Red, Green, Blue, Black. Material: Latex Resistance Bands', 699, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Equipment', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 45),
  ('Decathlon Jump Rope - Speed', 'Decathlon speed jump rope with ball bearings. Smooth rotation. Adjustable length. Colors: Black, Red, Blue. Material: PVC Rope with Ball Bearings', 399, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Equipment', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 50),
  ('Cult.fit Kettlebell - Cast Iron', 'Cult.fit cast iron kettlebell. Durable construction. Weights: 5kg, 8kg, 12kg, 16kg. Colors: Black, Grey. Material: Cast Iron', 1499, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Equipment', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 35),
  ('Decathlon Pull Up Bar - Doorway', 'Decathlon doorway pull up bar. Adjustable width. Supports up to 300lbs. Easy installation. Material: Durable Steel', 999, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Equipment', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 38),
  ('Cult.fit Foam Roller - Massage', 'Cult.fit massage foam roller. Muscle recovery. Size: 30cm, 45cm. Colors: Blue, Black, Pink. Material: High Density EVA Foam', 799, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Equipment', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 42),
  ('Decathlon Ab Roller Wheel', 'Decathlon ab roller wheel with knee pad. Strengthens core. Colors: Black, Red, Blue. Material: Durable Plastic with Foam Pad', 599, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Equipment', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 44),
  ('Cult.fit Medicine Ball - Weighted', 'Cult.fit weighted medicine ball. Functional training. Weights: 2kg, 4kg, 6kg, 8kg. Colors: Black, Blue, Red. Material: Durable Rubber', 1299, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Equipment', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 32),
  ('Decathlon Exercise Ball - Stability', 'Decathlon stability exercise ball. Core strengthening. Sizes: 55cm, 65cm, 75cm. Colors: Blue, Red, Green, Black. Material: Anti-Burst PVC', 899, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Equipment', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 36),
  
  -- Fitness Accessories (8 products)
  ('Fastrack Fitness Tracker - Wristband', 'Fastrack wristband fitness tracker with heart rate monitor. Activity tracking. Colors: Black, Blue, Pink, Green. Material: Silicone Band', 1999, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Fitness Accessories', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 30),
  ('Milton Water Bottle - Sports', 'Milton sports water bottle 750ml. Leak-proof. Colors: Blue, Black, Green, Red. Material: Food-Grade Plastic', 499, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Fitness Accessories', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 45),
  ('Decathlon Gym Towel - Microfiber', 'Decathlon microfiber gym towel. Quick-dry. Size: 30x60cm. Colors: Black, Grey, Blue. Material: Microfiber Fabric', 299, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Fitness Accessories', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 50),
  ('Cult.fit Weight Lifting Gloves', 'Cult.fit weight lifting gloves with padding. Hand protection. Sizes: S, M, L, XL. Colors: Black, Grey. Material: Leather with Padding', 599, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Fitness Accessories', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 40),
  ('Decathlon Yoga Block Set - 2 Pieces', 'Decathlon yoga block set with 2 pieces. Perfect for yoga practice. Colors: Purple, Blue, Pink, Green. Material: EVA Foam', 499, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Fitness Accessories', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 42),
  ('Skybags Gym Bag - Large', 'Skybags large gym bag with shoe compartment. Spacious design. Colors: Black, Navy, Grey, Red. Material: Durable Polyester', 899, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Fitness Accessories', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 38),
  ('Milton Protein Shaker Bottle', 'Milton protein shaker bottle 700ml. Leak-proof design. Colors: Black, Blue, Red, Green. Material: Food-Grade Plastic', 399, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Fitness Accessories', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 44),
  ('Cult.fit Wrist Wraps - Support', 'Cult.fit wrist wraps for weightlifting support. Prevents injury. Colors: Black, Red, Blue. One size. Material: Elastic Fabric', 499, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Fitness Accessories', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800', 40),
  
  -- Sports Shoes (5 products)
  ('Nike Running Shoes - Cushioned', 'Nike cushioned running shoes for long distance. Maximum comfort. Sizes: 6-11. Colors: White, Black, Blue, Red. Material: Synthetic Upper, Cushioned Sole', 3999, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sports Shoes', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', 28),
  ('Adidas Basketball Shoes - High Top', 'Adidas high-top basketball shoes. Ankle support. Sizes: 6-11. Colors: Black, White, Red, Blue. Material: Synthetic Upper, Rubber Sole', 4499, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sports Shoes', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', 25),
  ('Reebok Training Shoes - Crossfit', 'Reebok crossfit training shoes. Versatile design. Sizes: 6-11. Colors: Black, Grey, Red, Blue. Material: Durable Synthetic Upper', 3499, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sports Shoes', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', 30),
  ('Puma Walking Shoes - Comfort', 'Puma comfortable walking shoes. Cushioned sole. Sizes: 6-11. Colors: White, Black, Grey, Navy. Material: Synthetic Upper, Comfort Sole', 2999, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sports Shoes', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', 32),
  ('Nike Tennis Shoes - Court', 'Nike court tennis shoes. Non-marking sole. Sizes: 6-11. Colors: White, Black, Blue. Material: Synthetic Upper, Non-Marking Rubber Sole', 3299, (SELECT id FROM categories WHERE slug = 'sports-fitness'), 'Sports Shoes', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', 28);

-- ============================================
-- 9. STATIONERY & OFFICE (35+ products)
-- Brands: Classmate, Apsara, Camlin, Parker | Types: Notebooks, Pens, Office Supplies
-- Price Range: ₹99 - ₹1999 | Sizes: Various (A4, A5 for notebooks, Standard sizes)
-- ============================================
INSERT INTO public.products (name, description, price, category_id, subcategory, image_url, stock) VALUES
  -- Notebooks (10 products)
  ('Classmate Spiral Notebook - Ruled', 'Classmate ruled spiral notebook. Durable binding. Size: A4, A5. Pages: 100, 200. Colors: Blue, Red, Green, Black cover. Material: Quality Paper', 199, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Notebooks', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 60),
  ('Classmate Hardcover Notebook - Journal', 'Classmate hardcover journal notebook. Premium quality. Size: A5. Pages: 200. Colors: Black, Brown, Blue, Red cover. Material: Quality Paper with Hard Cover', 499, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Notebooks', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 45),
  ('Classmate Notebook Set - Pack of 5', 'Classmate notebook set pack of 5. Value for money. Size: A4. Pages: 100 each. Multiple cover colors. Material: Quality Paper', 399, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Notebooks', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 50),
  ('Classmate Bullet Journal - Dotted', 'Classmate dotted bullet journal. Perfect for planning. Size: A5. Pages: 200. Colors: Black, Navy, Pink, Green cover. Material: Quality Paper', 599, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Notebooks', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 40),
  ('Classmate Sketchbook - Blank', 'Classmate blank sketchbook for drawing. Perfect for artists. Size: A4, A5. Pages: 100. Colors: White, Cream. Material: Quality Drawing Paper', 349, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Notebooks', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 42),
  ('Classmate Notebook - Lined', 'Classmate lined notebook. Standard ruled pages. Size: A4. Pages: 150. Colors: Blue, Red, Green, Yellow cover. Material: Quality Paper', 249, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Notebooks', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 55),
  ('Classmate Composition Book - Classic', 'Classmate classic composition book. Traditional design. Size: A4. Pages: 100. Colors: Black, Red, Blue cover. Material: Quality Paper', 179, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Notebooks', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 58),
  ('Classmate Notebook - Grid', 'Classmate grid notebook for technical work. Perfect for math and engineering. Size: A4. Pages: 100. Colors: Blue, Black cover. Material: Quality Grid Paper', 299, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Notebooks', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 48),
  ('Classmate Notebook - Leather Bound', 'Classmate premium leather bound notebook. Elegant design. Size: A5. Pages: 200. Colors: Brown, Black, Tan. Material: Genuine Leather Cover', 899, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Notebooks', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 30),
  ('Classmate Notebook Set - College Ruled', 'Classmate college ruled notebook set. Standard spacing. Size: A4. Pages: 150 each. Pack of 3. Multiple colors. Material: Quality Paper', 449, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Notebooks', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 38),
  
  -- Pens (10 products)
  ('Reynolds Ball Pen Set - Pack of 10', 'Reynolds ball pen set pack of 10. Smooth writing. Colors: Blue, Black, Red, Green. Material: Quality Ink', 199, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Pens', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 70),
  ('Cello Gel Pen Set - 12 Colors', 'Cello gel pen set with 12 colors. Smooth ink flow. Multiple color options. Material: Gel Ink', 299, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Pens', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 65),
  ('Parker Fountain Pen - Premium', 'Parker premium fountain pen. Elegant writing. Colors: Black, Blue, Red. Refillable. Material: Premium Metal Body', 1999, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Pens', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 25),
  ('Apsara Rollerball Pen - Smooth', 'Apsara smooth rollerball pen. Comfortable grip. Colors: Blue, Black, Red. Material: Quality Rollerball Mechanism', 399, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Pens', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 55),
  ('Camlin Marker Pen Set - 8 Colors', 'Camlin marker pen set with 8 colors. Permanent ink. Multiple color options. Material: Permanent Marker Ink', 249, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Pens', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 60),
  ('Cello Highlighter Set - 5 Colors', 'Cello highlighter set with 5 colors. Bright colors. Colors: Yellow, Pink, Green, Blue, Orange. Material: Fluorescent Ink', 199, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Pens', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 68),
  ('Camlin Technical Pen Set - 3 Sizes', 'Camlin technical pen set with 3 sizes. For drawing and drafting. Colors: Black. Material: Technical Ink', 599, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Pens', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 35),
  ('Parker Calligraphy Pen Set', 'Parker calligraphy pen set with multiple nibs. Artistic writing. Colors: Black, Blue ink. Material: Calligraphy Nibs', 899, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Pens', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 32),
  ('Parker Pen Set - Executive', 'Parker executive pen set with 2 pens. Premium quality. Colors: Black, Silver. Material: Premium Metal Body', 1299, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Pens', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 28),
  ('Apsara Pen Set - Professional', 'Apsara professional pen set. High quality. Colors: Blue, Black, Red, Green. Material: Quality Ink Mechanism', 499, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Pens', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 42),
  
  -- Office Supplies (8 products)
  ('Cello Stapler - Heavy Duty', 'Cello heavy duty stapler. Durable construction. Colors: Black, Red, Blue. Holds up to 50 sheets. Material: Metal Construction', 399, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Office Supplies', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 45),
  ('Apsara Paper Clip Set - Assorted', 'Apsara assorted paper clip set. Multiple sizes. Colors: Silver, Colored. Pack of 100. Material: Galvanized Steel', 99, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Office Supplies', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 80),
  ('Cello Binder Clips Set - 3 Sizes', 'Cello binder clips set with 3 sizes. Strong grip. Colors: Black. Pack of 12. Material: Durable Steel', 199, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Office Supplies', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 60),
  ('Apsara Desk Organizer - Multi Compartment', 'Apsara multi-compartment desk organizer. Keeps desk tidy. Colors: Black, White, Grey. Material: Durable Plastic', 699, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Office Supplies', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 38),
  ('Cello File Folder Set - 10 Pieces', 'Cello file folder set with 10 pieces. Organizes documents. Colors: Blue, Red, Green, Yellow. A4 size. Material: Durable Cardboard', 299, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Office Supplies', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 50),
  ('Apsara Sticky Notes Set - 5 Colors', 'Apsara sticky notes set with 5 colors. Removable adhesive. Colors: Yellow, Pink, Green, Blue, Orange. Pack of 10 pads. Material: Quality Paper', 249, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Office Supplies', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 55),
  ('Casio Calculator - Desktop', 'Casio desktop calculator with large display. Easy to use. Colors: Black, White, Grey. 12-digit display. Material: Durable Plastic', 599, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Office Supplies', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 40),
  ('Philips Desk Lamp - LED', 'Philips LED desk lamp with adjustable brightness. Eye-friendly light. Colors: Black, White, Silver. USB charging. Material: Metal and Plastic', 899, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Office Supplies', 'https://images.unsplash.com/photo-1583484963886-cce2f6959794?w=800', 35),
  
  -- Art Materials (7 products)
  ('Camlin Watercolor Paint Set - 24 Colors', 'Camlin watercolor paint set with 24 colors. High quality pigments. Includes brush. Material: Watercolor Paints', 799, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Art Materials', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 35),
  ('Apsara Acrylic Paint Set - 12 Colors', 'Apsara acrylic paint set with 12 colors. Primary and secondary colors. 12ml tubes. Material: Acrylic Paints', 599, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Art Materials', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 40),
  ('Camlin Paint Brush Set - 10 Pieces', 'Camlin paint brush set with 10 pieces. Multiple sizes. Synthetic and natural bristles. Material: Quality Bristles', 399, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Art Materials', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 45),
  ('Apsara Colored Pencil Set - 36 Colors', 'Apsara colored pencil set with 36 colors. High quality pigments. Smooth coloring. Material: Wax-Based Colored Pencils', 699, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Art Materials', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 38),
  ('Camlin Sketch Pencil Set - 12 Grades', 'Camlin sketch pencil set with 12 grades. From 6B to 6H. For drawing and shading. Material: Graphite Pencils', 299, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Art Materials', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 50),
  ('Apsara Canvas Set - 3 Pieces', 'Apsara canvas set with 3 pieces. Primed and ready. Sizes: 8x10, 10x12, 12x16 inches. Material: Primed Canvas', 499, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Art Materials', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 42),
  ('Camlin Eraser Set - 5 Pieces', 'Camlin eraser set with 5 pieces. Different types: Kneaded, Vinyl, Pencil. For various uses. Material: Quality Erasers', 149, (SELECT id FROM categories WHERE slug = 'stationery-office'), 'Art Materials', 'https://images.unsplash.com/photo-1532619675605-1ede6c9ed2d7?w=800', 65);

-- Total: 315+ products across all 9 categories
-- All products include Indian brands, specific styles, size variations, and realistic pricing


